
package com.mycompany.projectguitrying;

/**
 *
 * @author SHAFAY
 */
public class QuestionBank extends javax.swing.JFrame {

    /**
     * Creates new form QuestionBank
     */
    String teacher;
    String student;
    String selectedCourse;
    public QuestionBank(String teacher, String student,String selectedCourse) {
        this.teacher=teacher;
        this.student=student;
        this.selectedCourse=selectedCourse;
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidebar = new javax.swing.JPanel();
        HomeSideButtonPanel = new javax.swing.JPanel();
        HomeSideButton = new javax.swing.JButton();
        StartQuizSideButtonPanel = new javax.swing.JPanel();
        StartQuizSideButton = new javax.swing.JButton();
        TeachersSideButtonPanel = new javax.swing.JPanel();
        TeachersSideButton = new javax.swing.JButton();
        StudentsSideButtonPanel = new javax.swing.JPanel();
        StudentsSideButton = new javax.swing.JButton();
        AboutUsSideButtonPanel = new javax.swing.JPanel();
        AboutUsSideButton = new javax.swing.JButton();
        SideBarQuizLabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        ExitSideButtonPanel = new javax.swing.JPanel();
        ExitSideButton = new javax.swing.JButton();
        QuestionBank = new javax.swing.JPanel();
        QuestionBankHeader = new javax.swing.JPanel();
        QuestionBankHeaderLabel = new javax.swing.JLabel();
        EnterMcq1Label = new javax.swing.JLabel();
        Mcq1OptionALabel = new javax.swing.JLabel();
        Mcq1OptionBLabel = new javax.swing.JLabel();
        Mcq1OptionCLabel = new javax.swing.JLabel();
        Mcq1OptionDLabel = new javax.swing.JLabel();
        EnterMcq2Label = new javax.swing.JLabel();
        Mcq2OptionALabel = new javax.swing.JLabel();
        Mcq2OptionBLabel = new javax.swing.JLabel();
        Mcq2OptionCLabel = new javax.swing.JLabel();
        Mcq2OptionDLabel = new javax.swing.JLabel();
        EnterMcq3Label = new javax.swing.JLabel();
        EnterMcq4Label = new javax.swing.JLabel();
        Mcq3OptionCLabel = new javax.swing.JLabel();
        Mcq4OptionCLabel = new javax.swing.JLabel();
        Mcq4OptionDLabel = new javax.swing.JLabel();
        Mcq3OptionDLabel = new javax.swing.JLabel();
        Mcq3OptionALabel = new javax.swing.JLabel();
        Mcq4OptionALabel = new javax.swing.JLabel();
        Mcq4OptionBLabel = new javax.swing.JLabel();
        Mcq3OptionBLabel = new javax.swing.JLabel();
        Mcq4OptionATextfield = new javax.swing.JTextField();
        Mcq4OptionBTextfield = new javax.swing.JTextField();
        Mcq4OptionCTextfield = new javax.swing.JTextField();
        Mcq4OptionDTextfield = new javax.swing.JTextField();
        Mcq1Textfield = new javax.swing.JTextField();
        Mcq3OptionATextfield = new javax.swing.JTextField();
        Mcq3OptionBTextfield = new javax.swing.JTextField();
        Mcq3OptionCTextfield = new javax.swing.JTextField();
        Mcq3OptionDTextfield = new javax.swing.JTextField();
        Mcq2OptionATextfield = new javax.swing.JTextField();
        Mcq2OptionCTextfield = new javax.swing.JTextField();
        Mcq2OptionBTextfield = new javax.swing.JTextField();
        Mcq2OptionDTextfield = new javax.swing.JTextField();
        Mcq1OptionDTextfield = new javax.swing.JTextField();
        Mcq1OptionCTextfield = new javax.swing.JTextField();
        Mcq1OptionBTextfield = new javax.swing.JTextField();
        Mcq1OptionATextfield = new javax.swing.JTextField();
        EnterTf1Label = new javax.swing.JLabel();
        Tf1Textfield = new javax.swing.JTextField();
        EnterTf2Label = new javax.swing.JLabel();
        Tf2Textfield = new javax.swing.JTextField();
        Tf3Textfield = new javax.swing.JTextField();
        EnterTf3Label = new javax.swing.JLabel();
        Tf1CorrectOptionLabel = new javax.swing.JLabel();
        Tf2CorrectOptionLabel = new javax.swing.JLabel();
        Tf3CorrectOptionLabel = new javax.swing.JLabel();
        QuestionBankPreprationNextButton = new javax.swing.JButton();
        QuestionBankNote1 = new javax.swing.JLabel();
        QuestionBankNote2 = new javax.swing.JLabel();
        Mcq1CorrectOptionLabel = new javax.swing.JLabel();
        Mcq1CorrectOptionComboBox = new javax.swing.JComboBox<>();
        Mcq2Textfield = new javax.swing.JTextField();
        Mcq2CorrectOptionLabel = new javax.swing.JLabel();
        Mcq2CorrectOptionComboBox = new javax.swing.JComboBox<>();
        Mcq3Textfield = new javax.swing.JTextField();
        Mcq3CorrectOptionLabel = new javax.swing.JLabel();
        Mcq3CorrectOptionComboBox = new javax.swing.JComboBox<>();
        Mcq4Textfield = new javax.swing.JTextField();
        Mcq4CorrectOptionLabel = new javax.swing.JLabel();
        Mcq4CorrectOptionComboBox = new javax.swing.JComboBox<>();
        QuestionBankBottom = new javax.swing.JPanel();
        QuestionBankBottomLabel = new javax.swing.JLabel();
        Tf1CorrectOptionComboBox = new javax.swing.JComboBox<>();
        Tf2CorrectOptionComboBox = new javax.swing.JComboBox<>();
        Tf3CorrectOptionComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(50, 0));

        sidebar.setBackground(new java.awt.Color(255, 255, 105));
        sidebar.setBorder(javax.swing.BorderFactory.createMatteBorder(8, 8, 8, 8, new java.awt.Color(0, 0, 0)));

        HomeSideButtonPanel.setBackground(new java.awt.Color(255, 204, 0));


        HomeSideButton.setBackground(new java.awt.Color(255, 204, 0));
        HomeSideButton.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        HomeSideButton.setText("HOME");
        HomeSideButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        HomeSideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeSideButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout HomeSideButtonPanelLayout = new javax.swing.GroupLayout(HomeSideButtonPanel);
        HomeSideButtonPanel.setLayout(HomeSideButtonPanelLayout);
        HomeSideButtonPanelLayout.setHorizontalGroup(
            HomeSideButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeSideButtonPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(HomeSideButton, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        HomeSideButtonPanelLayout.setVerticalGroup(
            HomeSideButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomeSideButtonPanelLayout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(HomeSideButton)
                .addGap(15, 15, 15))
        );

        StartQuizSideButtonPanel.setBackground(new java.awt.Color(255, 204, 0));

        StartQuizSideButton.setBackground(new java.awt.Color(255, 205, 0));
        StartQuizSideButton.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        StartQuizSideButton.setText("START QUIZ");
        StartQuizSideButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        StartQuizSideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartQuizSideButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout StartQuizSideButtonPanelLayout = new javax.swing.GroupLayout(StartQuizSideButtonPanel);
        StartQuizSideButtonPanel.setLayout(StartQuizSideButtonPanelLayout);
        StartQuizSideButtonPanelLayout.setHorizontalGroup(
            StartQuizSideButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StartQuizSideButtonPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(StartQuizSideButton, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        StartQuizSideButtonPanelLayout.setVerticalGroup(
            StartQuizSideButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StartQuizSideButtonPanelLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(StartQuizSideButton)
                .addGap(14, 14, 14))
        );

        TeachersSideButtonPanel.setBackground(new java.awt.Color(255, 204, 0));


        TeachersSideButton.setBackground(new java.awt.Color(255, 205, 0));
        TeachersSideButton.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        TeachersSideButton.setText("TEACHERS");
        TeachersSideButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        TeachersSideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeachersSideButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TeachersSideButtonPanelLayout = new javax.swing.GroupLayout(TeachersSideButtonPanel);
        TeachersSideButtonPanel.setLayout(TeachersSideButtonPanelLayout);
        TeachersSideButtonPanelLayout.setHorizontalGroup(
            TeachersSideButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TeachersSideButtonPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(TeachersSideButton, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TeachersSideButtonPanelLayout.setVerticalGroup(
            TeachersSideButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TeachersSideButtonPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(TeachersSideButton)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        StudentsSideButtonPanel.setBackground(new java.awt.Color(255, 204, 0));


        StudentsSideButton.setBackground(new java.awt.Color(255, 205, 0));
        StudentsSideButton.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        StudentsSideButton.setText("STUDENTS");
        StudentsSideButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        StudentsSideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentsSideButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout StudentsSideButtonPanelLayout = new javax.swing.GroupLayout(StudentsSideButtonPanel);
        StudentsSideButtonPanel.setLayout(StudentsSideButtonPanelLayout);
        StudentsSideButtonPanelLayout.setHorizontalGroup(
            StudentsSideButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentsSideButtonPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(StudentsSideButton, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        StudentsSideButtonPanelLayout.setVerticalGroup(
            StudentsSideButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentsSideButtonPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(StudentsSideButton)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        AboutUsSideButtonPanel.setBackground(new java.awt.Color(255, 204, 0));


        AboutUsSideButton.setBackground(new java.awt.Color(255, 205, 0));
        AboutUsSideButton.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        AboutUsSideButton.setText("ABOUT US");
        AboutUsSideButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        AboutUsSideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutUsSideButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AboutUsSideButtonPanelLayout = new javax.swing.GroupLayout(AboutUsSideButtonPanel);
        AboutUsSideButtonPanel.setLayout(AboutUsSideButtonPanelLayout);
        AboutUsSideButtonPanelLayout.setHorizontalGroup(
            AboutUsSideButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AboutUsSideButtonPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(AboutUsSideButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AboutUsSideButtonPanelLayout.setVerticalGroup(
            AboutUsSideButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AboutUsSideButtonPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(AboutUsSideButton)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        SideBarQuizLabel.setFont(new java.awt.Font("Tw Cen MT", 3, 48)); // NOI18N
        SideBarQuizLabel.setText("QUIZ");

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N

        ExitSideButtonPanel.setBackground(new java.awt.Color(255, 204, 0));


        ExitSideButton.setBackground(new java.awt.Color(255, 205, 0));
        ExitSideButton.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        ExitSideButton.setText("EXIT");
        ExitSideButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        ExitSideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitSideButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ExitSideButtonPanelLayout = new javax.swing.GroupLayout(ExitSideButtonPanel);
        ExitSideButtonPanel.setLayout(ExitSideButtonPanelLayout);
        ExitSideButtonPanelLayout.setHorizontalGroup(
            ExitSideButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ExitSideButtonPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(ExitSideButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ExitSideButtonPanelLayout.setVerticalGroup(
            ExitSideButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ExitSideButtonPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(ExitSideButton)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout sidebarLayout = new javax.swing.GroupLayout(sidebar);
        sidebar.setLayout(sidebarLayout);
        sidebarLayout.setHorizontalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HomeSideButtonPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(TeachersSideButtonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(StartQuizSideButtonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(StudentsSideButtonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidebarLayout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addGroup(sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sidebarLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(SideBarQuizLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60))
            .addComponent(AboutUsSideButtonPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ExitSideButtonPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        sidebarLayout.setVerticalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarLayout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(SideBarQuizLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138)
                .addComponent(HomeSideButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StartQuizSideButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TeachersSideButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StudentsSideButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AboutUsSideButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ExitSideButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(160, Short.MAX_VALUE))
        );

        QuestionBank.setBackground(new java.awt.Color(0, 0, 0));
        QuestionBank.setBorder(javax.swing.BorderFactory.createMatteBorder(8, 0, 8, 8, new java.awt.Color(0, 0, 0)));

        QuestionBankHeader.setBackground(new java.awt.Color(255, 255, 105));

        QuestionBankHeaderLabel.setBackground(new java.awt.Color(255, 255, 105));
        QuestionBankHeaderLabel.setFont(new java.awt.Font("Tw Cen MT", 3, 36)); // NOI18N
        QuestionBankHeaderLabel.setText("QUIZ QUESTION BANK PREPRATION!");

        javax.swing.GroupLayout QuestionBankHeaderLayout = new javax.swing.GroupLayout(QuestionBankHeader);
        QuestionBankHeader.setLayout(QuestionBankHeaderLayout);
        QuestionBankHeaderLayout.setHorizontalGroup(
            QuestionBankHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuestionBankHeaderLayout.createSequentialGroup()
                .addGap(452, 452, 452)
                .addComponent(QuestionBankHeaderLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        QuestionBankHeaderLayout.setVerticalGroup(
            QuestionBankHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuestionBankHeaderLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(QuestionBankHeaderLabel)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        EnterMcq1Label.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EnterMcq1Label.setForeground(new java.awt.Color(255, 255, 255));
        EnterMcq1Label.setText("Enter MCQ 1:");

        Mcq1OptionALabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Mcq1OptionALabel.setForeground(new java.awt.Color(255, 255, 255));
        Mcq1OptionALabel.setText("OPTION A:");

        Mcq1OptionBLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Mcq1OptionBLabel.setForeground(new java.awt.Color(255, 255, 255));
        Mcq1OptionBLabel.setText("OPTION B:");

        Mcq1OptionCLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Mcq1OptionCLabel.setForeground(new java.awt.Color(255, 255, 255));
        Mcq1OptionCLabel.setText("OPTION C:");

        Mcq1OptionDLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Mcq1OptionDLabel.setForeground(new java.awt.Color(255, 255, 255));
        Mcq1OptionDLabel.setText("OPTION D:");

        EnterMcq2Label.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EnterMcq2Label.setForeground(new java.awt.Color(255, 255, 255));
        EnterMcq2Label.setText("Enter MCQ 2:");

        Mcq2OptionALabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Mcq2OptionALabel.setForeground(new java.awt.Color(255, 255, 255));
        Mcq2OptionALabel.setText("OPTION A:");

        Mcq2OptionBLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Mcq2OptionBLabel.setForeground(new java.awt.Color(255, 255, 255));
        Mcq2OptionBLabel.setText("OPTION B:");

        Mcq2OptionCLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Mcq2OptionCLabel.setForeground(new java.awt.Color(255, 255, 255));
        Mcq2OptionCLabel.setText("OPTION C:");

        Mcq2OptionDLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Mcq2OptionDLabel.setForeground(new java.awt.Color(255, 255, 255));
        Mcq2OptionDLabel.setText("OPTION D:");

        EnterMcq3Label.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EnterMcq3Label.setForeground(new java.awt.Color(255, 255, 255));
        EnterMcq3Label.setText("Enter MCQ 3:");

        EnterMcq4Label.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EnterMcq4Label.setForeground(new java.awt.Color(255, 255, 255));
        EnterMcq4Label.setText("Enter MCQ 4:");

        Mcq3OptionCLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Mcq3OptionCLabel.setForeground(new java.awt.Color(255, 255, 255));
        Mcq3OptionCLabel.setText("OPTION C:");

        Mcq4OptionCLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Mcq4OptionCLabel.setForeground(new java.awt.Color(255, 255, 255));
        Mcq4OptionCLabel.setText("OPTION C:");

        Mcq4OptionDLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Mcq4OptionDLabel.setForeground(new java.awt.Color(255, 255, 255));
        Mcq4OptionDLabel.setText("OPTION D:");

        Mcq3OptionDLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Mcq3OptionDLabel.setForeground(new java.awt.Color(255, 255, 255));
        Mcq3OptionDLabel.setText("OPTION D:");

        Mcq3OptionALabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Mcq3OptionALabel.setForeground(new java.awt.Color(255, 255, 255));
        Mcq3OptionALabel.setText("OPTION A:");

        Mcq4OptionALabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Mcq4OptionALabel.setForeground(new java.awt.Color(255, 255, 255));
        Mcq4OptionALabel.setText("OPTION A:");

        Mcq4OptionBLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Mcq4OptionBLabel.setForeground(new java.awt.Color(255, 255, 255));
        Mcq4OptionBLabel.setText("OPTION B:");

        Mcq3OptionBLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Mcq3OptionBLabel.setForeground(new java.awt.Color(255, 255, 255));
        Mcq3OptionBLabel.setText("OPTION B:");

        Mcq4OptionATextfield.setBackground(new java.awt.Color(255, 204, 0));
        Mcq4OptionATextfield.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Mcq4OptionATextfield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        Mcq4OptionATextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mcq4OptionATextfieldActionPerformed(evt);
            }
        });

        Mcq4OptionBTextfield.setBackground(new java.awt.Color(255, 204, 0));
        Mcq4OptionBTextfield.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Mcq4OptionBTextfield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        Mcq4OptionBTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mcq4OptionBTextfieldActionPerformed(evt);
            }
        });

        Mcq4OptionCTextfield.setBackground(new java.awt.Color(255, 204, 0));
        Mcq4OptionCTextfield.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Mcq4OptionCTextfield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        Mcq4OptionCTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mcq4OptionCTextfieldActionPerformed(evt);
            }
        });

        Mcq4OptionDTextfield.setBackground(new java.awt.Color(255, 204, 0));
        Mcq4OptionDTextfield.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Mcq4OptionDTextfield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        Mcq4OptionDTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mcq4OptionDTextfieldActionPerformed(evt);
            }
        });

        Mcq1Textfield.setBackground(new java.awt.Color(255, 204, 0));
        Mcq1Textfield.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Mcq1Textfield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        Mcq1Textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mcq1TextfieldActionPerformed(evt);
            }
        });

        Mcq3OptionATextfield.setBackground(new java.awt.Color(255, 204, 0));
        Mcq3OptionATextfield.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Mcq3OptionATextfield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        Mcq3OptionATextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mcq3OptionATextfieldActionPerformed(evt);
            }
        });

        Mcq3OptionBTextfield.setBackground(new java.awt.Color(255, 204, 0));
        Mcq3OptionBTextfield.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Mcq3OptionBTextfield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        Mcq3OptionBTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mcq3OptionBTextfieldActionPerformed(evt);
            }
        });

        Mcq3OptionCTextfield.setBackground(new java.awt.Color(255, 204, 0));
        Mcq3OptionCTextfield.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Mcq3OptionCTextfield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        Mcq3OptionCTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mcq3OptionCTextfieldActionPerformed(evt);
            }
        });

        Mcq3OptionDTextfield.setBackground(new java.awt.Color(255, 204, 0));
        Mcq3OptionDTextfield.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Mcq3OptionDTextfield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        Mcq3OptionDTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mcq3OptionDTextfieldActionPerformed(evt);
            }
        });

        Mcq2OptionATextfield.setBackground(new java.awt.Color(255, 204, 0));
        Mcq2OptionATextfield.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Mcq2OptionATextfield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        Mcq2OptionATextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mcq2OptionATextfieldActionPerformed(evt);
            }
        });

        Mcq2OptionCTextfield.setBackground(new java.awt.Color(255, 204, 0));
        Mcq2OptionCTextfield.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Mcq2OptionCTextfield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        Mcq2OptionCTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mcq2OptionCTextfieldActionPerformed(evt);
            }
        });

        Mcq2OptionBTextfield.setBackground(new java.awt.Color(255, 204, 0));
        Mcq2OptionBTextfield.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Mcq2OptionBTextfield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        Mcq2OptionBTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mcq2OptionBTextfieldActionPerformed(evt);
            }
        });

        Mcq2OptionDTextfield.setBackground(new java.awt.Color(255, 204, 0));
        Mcq2OptionDTextfield.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Mcq2OptionDTextfield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        Mcq2OptionDTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mcq2OptionDTextfieldActionPerformed(evt);
            }
        });

        Mcq1OptionDTextfield.setBackground(new java.awt.Color(255, 204, 0));
        Mcq1OptionDTextfield.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Mcq1OptionDTextfield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        Mcq1OptionDTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mcq1OptionDTextfieldActionPerformed(evt);
            }
        });

        Mcq1OptionCTextfield.setBackground(new java.awt.Color(255, 204, 0));
        Mcq1OptionCTextfield.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Mcq1OptionCTextfield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        Mcq1OptionCTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mcq1OptionCTextfieldActionPerformed(evt);
            }
        });

        Mcq1OptionBTextfield.setBackground(new java.awt.Color(255, 204, 0));
        Mcq1OptionBTextfield.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Mcq1OptionBTextfield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        Mcq1OptionBTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mcq1OptionBTextfieldActionPerformed(evt);
            }
        });

        Mcq1OptionATextfield.setBackground(new java.awt.Color(255, 204, 0));
        Mcq1OptionATextfield.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Mcq1OptionATextfield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        Mcq1OptionATextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mcq1OptionATextfieldActionPerformed(evt);
            }
        });

        EnterTf1Label.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EnterTf1Label.setForeground(new java.awt.Color(255, 255, 255));
        EnterTf1Label.setText("Enter TF 1:");

        Tf1Textfield.setBackground(new java.awt.Color(255, 204, 0));
        Tf1Textfield.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Tf1Textfield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        Tf1Textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tf1TextfieldActionPerformed(evt);
            }
        });

        EnterTf2Label.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EnterTf2Label.setForeground(new java.awt.Color(255, 255, 255));
        EnterTf2Label.setText("Enter TF 2:");

        Tf2Textfield.setBackground(new java.awt.Color(255, 204, 0));
        Tf2Textfield.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Tf2Textfield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        Tf2Textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tf2TextfieldActionPerformed(evt);
            }
        });

        Tf3Textfield.setBackground(new java.awt.Color(255, 204, 0));
        Tf3Textfield.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Tf3Textfield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        Tf3Textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tf3TextfieldActionPerformed(evt);
            }
        });

        EnterTf3Label.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EnterTf3Label.setForeground(new java.awt.Color(255, 255, 255));
        EnterTf3Label.setText("Enter TF 3:");

        Tf1CorrectOptionLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Tf1CorrectOptionLabel.setForeground(new java.awt.Color(255, 255, 255));
        Tf1CorrectOptionLabel.setText("CORRECT OPTION:");

        Tf2CorrectOptionLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Tf2CorrectOptionLabel.setForeground(new java.awt.Color(255, 255, 255));
        Tf2CorrectOptionLabel.setText("CORRECT OPTION:");

        Tf3CorrectOptionLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Tf3CorrectOptionLabel.setForeground(new java.awt.Color(255, 255, 255));
        Tf3CorrectOptionLabel.setText("CORRECT OPTION:");

        QuestionBankPreprationNextButton.setBackground(new java.awt.Color(255, 204, 0));
        QuestionBankPreprationNextButton.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        QuestionBankPreprationNextButton.setText("NEXT!");
        QuestionBankPreprationNextButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        QuestionBankPreprationNextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuestionBankPreprationNextButtonActionPerformed(evt);
            }
        });

        QuestionBankNote1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        QuestionBankNote1.setForeground(new java.awt.Color(255, 204, 51));
        QuestionBankNote1.setText("NOTE: Dear User! Please kindly fill all the fields and prepare all 7 questions for the question bank.");

        QuestionBankNote2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        QuestionBankNote2.setForeground(new java.awt.Color(255, 204, 51));
        QuestionBankNote2.setText(" you can later select the number of questions you want to include in your quiz. Thankyou!");

        Mcq1CorrectOptionLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Mcq1CorrectOptionLabel.setForeground(new java.awt.Color(255, 255, 255));
        Mcq1CorrectOptionLabel.setText("CORRECT OPTION:");

        Mcq1CorrectOptionComboBox.setBackground(new java.awt.Color(255, 204, 0));
        Mcq1CorrectOptionComboBox.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Mcq1CorrectOptionComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D" }));
        Mcq1CorrectOptionComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mcq1CorrectOptionComboBoxActionPerformed(evt);
            }
        });

        Mcq2Textfield.setBackground(new java.awt.Color(255, 204, 0));
        Mcq2Textfield.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Mcq2Textfield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        Mcq2Textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mcq2TextfieldActionPerformed(evt);
            }
        });

        Mcq2CorrectOptionLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Mcq2CorrectOptionLabel.setForeground(new java.awt.Color(255, 255, 255));
        Mcq2CorrectOptionLabel.setText("CORRECT OPTION:");

        Mcq2CorrectOptionComboBox.setBackground(new java.awt.Color(255, 204, 0));
        Mcq2CorrectOptionComboBox.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Mcq2CorrectOptionComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D" }));
        Mcq2CorrectOptionComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mcq2CorrectOptionComboBoxActionPerformed(evt);
            }
        });

        Mcq3Textfield.setBackground(new java.awt.Color(255, 204, 0));
        Mcq3Textfield.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Mcq3Textfield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        Mcq3Textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mcq3TextfieldActionPerformed(evt);
            }
        });

        Mcq3CorrectOptionLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Mcq3CorrectOptionLabel.setForeground(new java.awt.Color(255, 255, 255));
        Mcq3CorrectOptionLabel.setText("CORRECT OPTION:");

        Mcq3CorrectOptionComboBox.setBackground(new java.awt.Color(255, 204, 0));
        Mcq3CorrectOptionComboBox.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Mcq3CorrectOptionComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D" }));
        Mcq3CorrectOptionComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mcq3CorrectOptionComboBoxActionPerformed(evt);
            }
        });

        Mcq4Textfield.setBackground(new java.awt.Color(255, 204, 0));
        Mcq4Textfield.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Mcq4Textfield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        Mcq4Textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mcq4TextfieldActionPerformed(evt);
            }
        });

        Mcq4CorrectOptionLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Mcq4CorrectOptionLabel.setForeground(new java.awt.Color(255, 255, 255));
        Mcq4CorrectOptionLabel.setText("CORRECT OPTION:");

        Mcq4CorrectOptionComboBox.setBackground(new java.awt.Color(255, 204, 0));
        Mcq4CorrectOptionComboBox.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Mcq4CorrectOptionComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D" }));
        Mcq4CorrectOptionComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mcq4CorrectOptionComboBoxActionPerformed(evt);
            }
        });

        QuestionBankBottom.setBackground(new java.awt.Color(255, 255, 105));

        QuestionBankBottomLabel.setFont(new java.awt.Font("Tw Cen MT", 2, 24)); // NOI18N
        QuestionBankBottomLabel.setText("© QUIZ SYSTEM CREATED BY SHAFAY. ALL RIGHTS RESERVED!");

        javax.swing.GroupLayout QuestionBankBottomLayout = new javax.swing.GroupLayout(QuestionBankBottom);
        QuestionBankBottom.setLayout(QuestionBankBottomLayout);
        QuestionBankBottomLayout.setHorizontalGroup(
            QuestionBankBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, QuestionBankBottomLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(QuestionBankBottomLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 930, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );
        QuestionBankBottomLayout.setVerticalGroup(
            QuestionBankBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, QuestionBankBottomLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(QuestionBankBottomLabel)
                .addContainerGap())
        );

        Tf1CorrectOptionComboBox.setBackground(new java.awt.Color(255, 204, 0));
        Tf1CorrectOptionComboBox.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Tf1CorrectOptionComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "True", "False" }));
        Tf1CorrectOptionComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tf1CorrectOptionComboBoxActionPerformed(evt);
            }
        });

        Tf2CorrectOptionComboBox.setBackground(new java.awt.Color(255, 204, 0));
        Tf2CorrectOptionComboBox.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Tf2CorrectOptionComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "True", "False" }));
        Tf2CorrectOptionComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tf2CorrectOptionComboBoxActionPerformed(evt);
            }
        });

        Tf3CorrectOptionComboBox.setBackground(new java.awt.Color(255, 204, 0));
        Tf3CorrectOptionComboBox.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Tf3CorrectOptionComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "True", "False" }));
        Tf3CorrectOptionComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tf3CorrectOptionComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout QuestionBankLayout = new javax.swing.GroupLayout(QuestionBank);
        QuestionBank.setLayout(QuestionBankLayout);
        QuestionBankLayout.setHorizontalGroup(
            QuestionBankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(QuestionBankHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(QuestionBankLayout.createSequentialGroup()
                .addGroup(QuestionBankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(QuestionBankNote1)
                    .addGroup(QuestionBankLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(QuestionBankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(QuestionBankLayout.createSequentialGroup()
                                .addComponent(EnterMcq3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Mcq3Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(QuestionBankLayout.createSequentialGroup()
                                .addComponent(EnterMcq1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Mcq1Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(QuestionBankLayout.createSequentialGroup()
                                .addComponent(EnterMcq2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Mcq2Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(QuestionBankLayout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(QuestionBankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(QuestionBankLayout.createSequentialGroup()
                                        .addComponent(Mcq2OptionALabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Mcq2OptionATextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Mcq2OptionBLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Mcq2OptionBTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Mcq2OptionCLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Mcq2OptionCTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Mcq2OptionDLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Mcq2OptionDTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Mcq2CorrectOptionLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Mcq2CorrectOptionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(QuestionBankLayout.createSequentialGroup()
                                        .addComponent(Mcq1OptionALabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Mcq1OptionATextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Mcq1OptionBLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Mcq1OptionBTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Mcq1OptionCLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Mcq1OptionCTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Mcq1OptionDLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Mcq1OptionDTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Mcq1CorrectOptionLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Mcq1CorrectOptionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(QuestionBankLayout.createSequentialGroup()
                                        .addComponent(Mcq3OptionALabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Mcq3OptionATextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Mcq3OptionBLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Mcq3OptionBTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Mcq3OptionCLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Mcq3OptionCTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Mcq3OptionDLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Mcq3OptionDTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Mcq3CorrectOptionLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Mcq3CorrectOptionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(QuestionBankLayout.createSequentialGroup()
                                        .addComponent(Mcq4OptionALabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Mcq4OptionATextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Mcq4OptionBLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Mcq4OptionBTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Mcq4OptionCLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Mcq4OptionCTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Mcq4OptionDLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Mcq4OptionDTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Mcq4CorrectOptionLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Mcq4CorrectOptionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(QuestionBankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, QuestionBankLayout.createSequentialGroup()
                                    .addComponent(EnterTf1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Tf1Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Tf1CorrectOptionLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Tf1CorrectOptionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(QuestionBankLayout.createSequentialGroup()
                                    .addComponent(EnterTf2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Tf2Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Tf2CorrectOptionLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Tf2CorrectOptionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(128, 128, 128)))
                            .addComponent(QuestionBankNote2, javax.swing.GroupLayout.PREFERRED_SIZE, 966, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(QuestionBankLayout.createSequentialGroup()
                                .addComponent(EnterMcq4Label, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Mcq4Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(QuestionBankLayout.createSequentialGroup()
                                .addComponent(EnterTf3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Tf3Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Tf3CorrectOptionLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Tf3CorrectOptionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(177, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, QuestionBankLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(QuestionBankPreprationNextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(575, 575, 575))
            .addComponent(QuestionBankBottom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        QuestionBankLayout.setVerticalGroup(
            QuestionBankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, QuestionBankLayout.createSequentialGroup()
                .addComponent(QuestionBankHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(QuestionBankNote1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(QuestionBankNote2)
                .addGap(47, 47, 47)
                .addGroup(QuestionBankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Mcq1Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EnterMcq1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(QuestionBankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Mcq1OptionALabel)
                    .addComponent(Mcq1OptionATextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Mcq1OptionBLabel)
                    .addComponent(Mcq1OptionBTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Mcq1OptionCLabel)
                    .addComponent(Mcq1OptionCTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Mcq1OptionDLabel)
                    .addComponent(Mcq1OptionDTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Mcq1CorrectOptionLabel)
                    .addComponent(Mcq1CorrectOptionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(QuestionBankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EnterMcq2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Mcq2Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(QuestionBankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Mcq2OptionBTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Mcq2OptionATextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Mcq2OptionALabel)
                    .addComponent(Mcq2OptionCLabel)
                    .addComponent(Mcq2OptionCTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Mcq2OptionDLabel)
                    .addComponent(Mcq2OptionDTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Mcq2OptionBLabel)
                    .addComponent(Mcq2CorrectOptionLabel)
                    .addComponent(Mcq2CorrectOptionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(QuestionBankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EnterMcq3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Mcq3Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(QuestionBankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Mcq3OptionCLabel)
                    .addComponent(Mcq3OptionDLabel)
                    .addComponent(Mcq3OptionALabel)
                    .addComponent(Mcq3OptionBLabel)
                    .addComponent(Mcq3OptionATextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Mcq3OptionBTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Mcq3OptionCTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Mcq3OptionDTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Mcq3CorrectOptionLabel)
                    .addComponent(Mcq3CorrectOptionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(QuestionBankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EnterMcq4Label, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Mcq4Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(QuestionBankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Mcq4OptionCLabel)
                    .addComponent(Mcq4OptionDLabel)
                    .addComponent(Mcq4OptionALabel)
                    .addComponent(Mcq4OptionBLabel)
                    .addComponent(Mcq4OptionBTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Mcq4OptionCTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Mcq4OptionDTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Mcq4OptionATextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Mcq4CorrectOptionLabel)
                    .addComponent(Mcq4CorrectOptionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(QuestionBankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EnterTf1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tf1Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tf1CorrectOptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tf1CorrectOptionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(QuestionBankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EnterTf2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tf2Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tf2CorrectOptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tf2CorrectOptionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(QuestionBankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tf3Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EnterTf3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tf3CorrectOptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tf3CorrectOptionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78)
                .addComponent(QuestionBankPreprationNextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(QuestionBankBottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sidebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(QuestionBank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sidebar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(QuestionBank, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomeSideButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeSideButtonActionPerformed
        // TODO add your handling code here:
        new homepage().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_HomeSideButtonActionPerformed



    private void StartQuizSideButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartQuizSideButtonActionPerformed

        // TODO add your handling code here:
        new QuizRegistration().setVisible(true);
        setVisible(false);

    }//GEN-LAST:event_StartQuizSideButtonActionPerformed



    private void TeachersSideButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeachersSideButtonActionPerformed
        new TeachersData().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_TeachersSideButtonActionPerformed



    private void StudentsSideButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentsSideButtonActionPerformed
        // TODO add your handling code here:
        new StudentsData().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_StudentsSideButtonActionPerformed



    private void AboutUsSideButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutUsSideButtonActionPerformed

        new AboutUs().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_AboutUsSideButtonActionPerformed



    private void ExitSideButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitSideButtonActionPerformed
        // TODO add your handling code here:

        setVisible(false);
    }//GEN-LAST:event_ExitSideButtonActionPerformed



    private void Mcq1TextfieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:


    }

    private void Mcq1OptionATextfieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:


    }

    private void Mcq1OptionBTextfieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:


    }

    private void Mcq1OptionCTextfieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:


    }

    private void Mcq1OptionDTextfieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:


    }

    private void Mcq1CorrectOptionComboBoxActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:


    }

    private void Mcq2TextfieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:


    }

    private void Mcq2OptionATextfieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:


    }

    private void Mcq2OptionBTextfieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:


    }

    private void Mcq2OptionCTextfieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:


    }

    private void Mcq2OptionDTextfieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:


    }

    private void Mcq2CorrectOptionComboBoxActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:


    }

    private void Mcq3TextfieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:


    }

    private void Mcq3OptionATextfieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:


    }

    private void Mcq3OptionBTextfieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:


    }

    private void Mcq3OptionCTextfieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:


    }

    private void Mcq3OptionDTextfieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:


    }

    private void Mcq3CorrectOptionComboBoxActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:


    }

    private void Mcq4TextfieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:


    }

    private void Mcq4OptionATextfieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:


    }

    private void Mcq4OptionBTextfieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:


    }

    private void Mcq4OptionCTextfieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:


    }

    private void Mcq4OptionDTextfieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:


    }

    private void Mcq4CorrectOptionComboBoxActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:


    }

    private void Tf1TextfieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:


    }

    private void Tf2TextfieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:


    }


    private void Tf3TextfieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:


    }
    private void Tf1CorrectOptionComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tf1CorrectOptionComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tf1CorrectOptionComboBoxActionPerformed

    private void Tf2CorrectOptionComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tf2CorrectOptionComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tf2CorrectOptionComboBoxActionPerformed

    private void Tf3CorrectOptionComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tf3CorrectOptionComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tf3CorrectOptionComboBoxActionPerformed


    private void QuestionBankPreprationNextButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        Mcq1 = Mcq1Textfield.getText();
        Mcq1optA = Mcq1OptionATextfield.getText();
        Mcq1optB = Mcq1OptionBTextfield.getText();
        Mcq1optC = Mcq1OptionCTextfield.getText();
        Mcq1optD = Mcq1OptionDTextfield.getText();
        Mcq1Correctopt = String.valueOf(Mcq1CorrectOptionComboBox.getSelectedItem());
        Mcq2 = Mcq2Textfield.getText();
        Mcq2optA = Mcq2OptionATextfield.getText();
        Mcq2optB = Mcq2OptionBTextfield.getText();
        Mcq2optC = Mcq2OptionCTextfield.getText();
        Mcq2optD = Mcq2OptionDTextfield.getText();
        Mcq2Correctopt = String.valueOf(Mcq1CorrectOptionComboBox.getSelectedItem());
        Mcq3 = Mcq3Textfield.getText();
        Mcq3optA = Mcq3OptionATextfield.getText();
        Mcq3optB = Mcq3OptionBTextfield.getText();
        Mcq3optC = Mcq3OptionCTextfield.getText();
        Mcq3optD = Mcq3OptionDTextfield.getText();
        Mcq3Correctopt = String.valueOf(Mcq1CorrectOptionComboBox.getSelectedItem());
        Mcq4 = Mcq4Textfield.getText();
        Mcq4optA = Mcq4OptionATextfield.getText();
        Mcq4optB = Mcq4OptionBTextfield.getText();
        Mcq4optC = Mcq4OptionCTextfield.getText();
        Mcq4optD = Mcq4OptionDTextfield.getText();
        Mcq4Correctopt = String.valueOf(Mcq1CorrectOptionComboBox.getSelectedItem());
        Tf1 = Tf1Textfield.getText();
        Tf1Correctopt = Tf1CorrectOptionComboBox.getSelectedItem().toString();
        Tf2 = Tf2Textfield.getText();
        Tf2Correctopt = String.valueOf(Tf2CorrectOptionComboBox.getSelectedItem());
        Tf3 = Tf3Textfield.getText();
        Tf3Correctopt = Tf3CorrectOptionComboBox.getSelectedItem().toString();



        new QuizSetting(Mcq1,Mcq1optA,Mcq1optB,Mcq1optC,Mcq1optD,Mcq1Correctopt,Mcq2,Mcq2optA,Mcq2optB,Mcq2optC,Mcq2optD,Mcq2Correctopt,Mcq3,Mcq3optA,Mcq3optB,Mcq3optC,Mcq3optD,Mcq3Correctopt,Mcq4,Mcq4optA,Mcq4optB,Mcq4optC,Mcq4optD,Mcq4Correctopt,Tf1,Tf1Correctopt,Tf2,Tf2Correctopt,Tf3,Tf3Correctopt,teacher,student,selectedCourse).setVisible(true);
    setVisible(false);
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuestionBank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuestionBank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuestionBank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuestionBank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public String Mcq1;
    public String Mcq1optA;
    public String Mcq1optB;
    public String Mcq1optC;
    public String Mcq1optD;
    public String Mcq1Correctopt;
    public String Mcq2;
    public String Mcq2optA;
    public String Mcq2optB;
    public String Mcq2optC;
    public String Mcq2optD;
    public String Mcq2Correctopt;
    public String Mcq3;
    public String Mcq3optA;
    public String Mcq3optB;
    public String Mcq3optC;
    public String Mcq3optD;
    public String Mcq3Correctopt;
    public String Mcq4;
    public String Mcq4optA;
    public String Mcq4optB;
    public String Mcq4optC;
    public String Mcq4optD;
    public String Mcq4Correctopt;
    public String Tf1;
    public String Tf1Correctopt;
    public String Tf2;
    public String Tf2Correctopt;
    public String Tf3;
    public String Tf3Correctopt;
    private javax.swing.JButton AboutUsSideButton;
    private javax.swing.JPanel AboutUsSideButtonPanel;
    private javax.swing.JButton QuestionBankPreprationNextButton;
    private javax.swing.JLabel EnterMcq1Label;
    private javax.swing.JLabel EnterMcq2Label;
    private javax.swing.JLabel EnterMcq3Label;
    private javax.swing.JLabel EnterMcq4Label;
    private javax.swing.JLabel EnterTf1Label;
    private javax.swing.JLabel EnterTf2Label;
    private javax.swing.JLabel EnterTf3Label;
    private javax.swing.JButton ExitSideButton;
    private javax.swing.JPanel ExitSideButtonPanel;
    private javax.swing.JButton HomeSideButton;
    private javax.swing.JPanel HomeSideButtonPanel;
    private javax.swing.JComboBox<String> Mcq1CorrectOptionComboBox;
    private javax.swing.JLabel Mcq1CorrectOptionLabel;
    private javax.swing.JLabel Mcq1OptionALabel;
    private javax.swing.JTextField Mcq1OptionATextfield;
    private javax.swing.JLabel Mcq1OptionBLabel;
    private javax.swing.JTextField Mcq1OptionBTextfield;
    private javax.swing.JLabel Mcq1OptionCLabel;
    private javax.swing.JTextField Mcq1OptionCTextfield;
    private javax.swing.JLabel Mcq1OptionDLabel;
    private javax.swing.JTextField Mcq1OptionDTextfield;
    private javax.swing.JTextField Mcq1Textfield;
    private javax.swing.JComboBox<String> Mcq2CorrectOptionComboBox;
    private javax.swing.JLabel Mcq2CorrectOptionLabel;
    private javax.swing.JLabel Mcq2OptionALabel;
    private javax.swing.JTextField Mcq2OptionATextfield;
    private javax.swing.JLabel Mcq2OptionBLabel;
    private javax.swing.JTextField Mcq2OptionBTextfield;
    private javax.swing.JLabel Mcq2OptionCLabel;
    private javax.swing.JTextField Mcq2OptionCTextfield;
    private javax.swing.JLabel Mcq2OptionDLabel;
    private javax.swing.JTextField Mcq2OptionDTextfield;
    private javax.swing.JTextField Mcq2Textfield;
    private javax.swing.JComboBox<String> Mcq3CorrectOptionComboBox;
    private javax.swing.JLabel Mcq3CorrectOptionLabel;
    private javax.swing.JLabel Mcq3OptionALabel;
    private javax.swing.JTextField Mcq3OptionATextfield;
    private javax.swing.JLabel Mcq3OptionBLabel;
    private javax.swing.JTextField Mcq3OptionBTextfield;
    private javax.swing.JLabel Mcq3OptionCLabel;
    private javax.swing.JTextField Mcq3OptionCTextfield;
    private javax.swing.JLabel Mcq3OptionDLabel;
    private javax.swing.JTextField Mcq3OptionDTextfield;
    private javax.swing.JTextField Mcq3Textfield;
    private javax.swing.JComboBox<String> Mcq4CorrectOptionComboBox;
    private javax.swing.JLabel Mcq4CorrectOptionLabel;
    private javax.swing.JLabel Mcq4OptionALabel;
    private javax.swing.JTextField Mcq4OptionATextfield;
    private javax.swing.JLabel Mcq4OptionBLabel;
    private javax.swing.JTextField Mcq4OptionBTextfield;
    private javax.swing.JLabel Mcq4OptionCLabel;
    private javax.swing.JTextField Mcq4OptionCTextfield;
    private javax.swing.JLabel Mcq4OptionDLabel;
    private javax.swing.JTextField Mcq4OptionDTextfield;
    private javax.swing.JTextField Mcq4Textfield;
    private javax.swing.JPanel QuestionBank;
    private javax.swing.JPanel QuestionBankBottom;
    private javax.swing.JLabel QuestionBankBottomLabel;
    private javax.swing.JPanel QuestionBankHeader;
    private javax.swing.JLabel QuestionBankHeaderLabel;
    private javax.swing.JLabel QuestionBankNote1;
    private javax.swing.JLabel QuestionBankNote2;
    private javax.swing.JLabel SideBarQuizLabel;
    private javax.swing.JButton StartQuizSideButton;
    private javax.swing.JPanel StartQuizSideButtonPanel;
    private javax.swing.JButton StudentsSideButton;
    private javax.swing.JPanel StudentsSideButtonPanel;
    private javax.swing.JButton TeachersSideButton;
    private javax.swing.JPanel TeachersSideButtonPanel;
    private javax.swing.JComboBox<String> Tf1CorrectOptionComboBox;
    private javax.swing.JLabel Tf1CorrectOptionLabel;
    private javax.swing.JTextField Tf1Textfield;
    private javax.swing.JComboBox<String> Tf2CorrectOptionComboBox;
    private javax.swing.JLabel Tf2CorrectOptionLabel;
    private javax.swing.JTextField Tf2Textfield;
    private javax.swing.JComboBox<String> Tf3CorrectOptionComboBox;
    private javax.swing.JLabel Tf3CorrectOptionLabel;
    private javax.swing.JTextField Tf3Textfield;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel sidebar;
    // End of variables declaration//GEN-END:variables
}
