
package com.mycompany.projectguitrying;

import javax.swing.*;

/**
 *
 * @author SHAFAY
 */
public class QuizStart extends javax.swing.JFrame {

    /**
     * Creates new form QuizStart
     */
    String numberofquestions;
    int marksofquestions;
    String day;
    String month;
    String year;
    String hour;
    String minute;
    String mcq1;
    String mcq1optA;
    String mcq1optB;
    String mcq1optC;
    String mcq1optD;
    String mcq1Correctopt;
    String mcq2;
    String mcq2optA;
    String mcq2optB;
    String mcq2optC;
    String mcq2optD;
    String mcq2Correctopt;
    String mcq3;
    String mcq3optA;
    String mcq3optB;
    String mcq3optC;
    String mcq3optD;
    String mcq3Correctopt;
    String mcq4;
    String mcq4optA;
    String mcq4optB;
    String mcq4optC;
    String mcq4optD;
    String mcq4Correctopt;
    String tf1;
    String tf1Correctopt;
    String tf2;
    String tf2Correctopt;
    String tf3;
    String tf3Correctopt;
    String teacher;
    String student;
    String selectedCourse;
    String CourseTopic1;



    public QuizStart(String CourseTopic1,String numberofquestions, String marksofquestions, String day, String month, String year, String hour, String minute, String mcq1, String mcq1optA, String mcq1optB, String mcq1optC, String mcq1optD, String mcq1Correctopt, String mcq2, String mcq2optA, String mcq2optB, String mcq2optC, String mcq2optD, String mcq2Correctopt, String mcq3, String mcq3optA, String mcq3optB, String mcq3optC, String mcq3optD, String mcq3Correctopt, String mcq4, String mcq4optA, String mcq4optB, String mcq4optC, String mcq4optD, String mcq4Correctopt, String tf1, String tf1Correctopt, String tf2, String tf2Correctopt, String tf3, String tf3Correctopt, String teacher, String student, String selectedCourse) {

        this.CourseTopic1=CourseTopic1;
        this.mcq1=mcq1;
        this.mcq1optA=mcq1optA;
        this.mcq1optB=mcq1optB;
        this.mcq1optC=mcq1optC;
        this.mcq1optD=mcq1optD;
        this.mcq1Correctopt=mcq1Correctopt;
        this.mcq2=mcq2;
        this.mcq2optA=mcq2optA;
        this.mcq2optB=mcq2optB;
        this.mcq2optC=mcq2optC;
        this.mcq2optD=mcq2optD;
        this.mcq2Correctopt=mcq2Correctopt;
        this.mcq3=mcq3;
        this.mcq3optA=mcq3optA;
        this.mcq3optB=mcq3optB;
        this.mcq3optC=mcq3optC;
        this.mcq3optD=mcq3optD;
        this.mcq3Correctopt=mcq3Correctopt;
        this.mcq4=mcq4;
        this.mcq4optA=mcq4optA;
        this.mcq4optB=mcq4optB;
        this.mcq4optC=mcq4optC;
        this.mcq4optD=mcq4optD;
        this.mcq4Correctopt=mcq4Correctopt;
        this.tf1=tf1;
        this.tf1Correctopt=tf1Correctopt;
        this.tf2=tf2;
        this.tf2Correctopt=tf2Correctopt;
        this.tf3=tf3;
        this.tf3Correctopt=tf3Correctopt;
        this.teacher=teacher;
        this.student=student;
        this.selectedCourse=selectedCourse;
        this.numberofquestions = numberofquestions;
        this.marksofquestions = Integer.parseInt(marksofquestions);
        this.day = day;
        this.month = month;
        this.year = year;
        this.hour = hour;
        this.minute = minute;
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        sidebar = new javax.swing.JPanel();
        HomeSideButtonPanel = new javax.swing.JPanel();
        HomeSideButton = new javax.swing.JButton();
        StartQuizSideButtonPanel = new javax.swing.JPanel();
        StartQuizSideButton = new javax.swing.JButton();
        TeachersSideButtonPanel = new javax.swing.JPanel();
        TeachersSideButton = new javax.swing.JButton();
        StudentsSideButtonPanel = new javax.swing.JPanel();
        StudentsSideButton = new javax.swing.JButton();
        AboutUsSideButtonPanel = new javax.swing.JPanel();
        AboutUsSideButton = new javax.swing.JButton();
        SideBarQuizLabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        ExitSideButtonPanel = new javax.swing.JPanel();
        ExitSideButton = new javax.swing.JButton();
        QuizStart = new javax.swing.JPanel();
        WelcomeStudentLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        QuizStartTotalMarksLabel = new javax.swing.JLabel();
        QuizStartQ2Panel = new javax.swing.JPanel();
        QuizStartQ2Mcq3Label = new javax.swing.JLabel();
        Q2Mcq3ComboBox = new javax.swing.JComboBox<>();
        QuizStartSubmitButton = new javax.swing.JButton();
        QuizStartQ1Panel = new javax.swing.JPanel();
        QuizStartQ1Mcq1Label = new javax.swing.JLabel();
        Q1Mcq1ComboBox = new javax.swing.JComboBox<>();
        QuizStartQ3Panel = new javax.swing.JPanel();
        QuizStartQ3Tf1Label = new javax.swing.JLabel();
        Q3Tf1ComboBox = new javax.swing.JComboBox<>();
        QuizStartQ4Panel = new javax.swing.JPanel();
        QuizStartQ4Tf3Label = new javax.swing.JLabel();
        Q4Tf3ComboBox = new javax.swing.JComboBox<>();
        QuizStartQ5Panel = new javax.swing.JPanel();
        QuizStartQ5Mcq2Label = new javax.swing.JLabel();
        Q5Mcq2ComboBox = new javax.swing.JComboBox<>();
        QuizStartQ6Panel = new javax.swing.JPanel();
        QuizStartQ6Tf2Label = new javax.swing.JLabel();
        Q6Tf2ComboBox = new javax.swing.JComboBox<>();
        QuizStartQ7Panel = new javax.swing.JPanel();
        QuizStartQ7Mcq4Label = new javax.swing.JLabel();
        Q7Mcq4ComboBox = new javax.swing.JComboBox<>();
        QuizStartTimeRemainingLabel = new javax.swing.JLabel();
        jSeparator15 = new javax.swing.JSeparator();
        jSeparator27 = new javax.swing.JSeparator();
        QuizStartHeader = new javax.swing.JPanel();
        QuizStartHeaderLabel = new javax.swing.JLabel();
        AboutUsBottom1 = new javax.swing.JPanel();
        AboutUsBottomLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sidebar.setBackground(new java.awt.Color(255, 255, 105));
        sidebar.setBorder(javax.swing.BorderFactory.createMatteBorder(8, 8, 8, 8, new java.awt.Color(0, 0, 0)));

        HomeSideButtonPanel.setBackground(new java.awt.Color(255, 204, 0));


        HomeSideButton.setBackground(new java.awt.Color(255, 204, 0));
        HomeSideButton.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        HomeSideButton.setText("HOME");
        HomeSideButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        HomeSideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeSideButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout HomeSideButtonPanelLayout = new javax.swing.GroupLayout(HomeSideButtonPanel);
        HomeSideButtonPanel.setLayout(HomeSideButtonPanelLayout);
        HomeSideButtonPanelLayout.setHorizontalGroup(
                HomeSideButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(HomeSideButtonPanelLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(HomeSideButton, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );
        HomeSideButtonPanelLayout.setVerticalGroup(
                HomeSideButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomeSideButtonPanelLayout.createSequentialGroup()
                                .addContainerGap(11, Short.MAX_VALUE)
                                .addComponent(HomeSideButton)
                                .addGap(15, 15, 15))
        );

        StartQuizSideButtonPanel.setBackground(new java.awt.Color(255, 204, 0));


        StartQuizSideButton.setBackground(new java.awt.Color(255, 205, 0));
        StartQuizSideButton.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        StartQuizSideButton.setText("START QUIZ");
        StartQuizSideButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        StartQuizSideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartQuizSideButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout StartQuizSideButtonPanelLayout = new javax.swing.GroupLayout(StartQuizSideButtonPanel);
        StartQuizSideButtonPanel.setLayout(StartQuizSideButtonPanelLayout);
        StartQuizSideButtonPanelLayout.setHorizontalGroup(
                StartQuizSideButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(StartQuizSideButtonPanelLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(StartQuizSideButton, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        StartQuizSideButtonPanelLayout.setVerticalGroup(
                StartQuizSideButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(StartQuizSideButtonPanelLayout.createSequentialGroup()
                                .addContainerGap(14, Short.MAX_VALUE)
                                .addComponent(StartQuizSideButton)
                                .addGap(14, 14, 14))
        );

        TeachersSideButtonPanel.setBackground(new java.awt.Color(255, 204, 0));


        TeachersSideButton.setBackground(new java.awt.Color(255, 205, 0));
        TeachersSideButton.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        TeachersSideButton.setText("TEACHERS");
        TeachersSideButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        TeachersSideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeachersSideButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TeachersSideButtonPanelLayout = new javax.swing.GroupLayout(TeachersSideButtonPanel);
        TeachersSideButtonPanel.setLayout(TeachersSideButtonPanelLayout);
        TeachersSideButtonPanelLayout.setHorizontalGroup(
                TeachersSideButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(TeachersSideButtonPanelLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(TeachersSideButton, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TeachersSideButtonPanelLayout.setVerticalGroup(
                TeachersSideButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(TeachersSideButtonPanelLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(TeachersSideButton)
                                .addContainerGap(15, Short.MAX_VALUE))
        );

        StudentsSideButtonPanel.setBackground(new java.awt.Color(255, 204, 0));


        StudentsSideButton.setBackground(new java.awt.Color(255, 205, 0));
        StudentsSideButton.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        StudentsSideButton.setText("STUDENTS");
        StudentsSideButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        StudentsSideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentsSideButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout StudentsSideButtonPanelLayout = new javax.swing.GroupLayout(StudentsSideButtonPanel);
        StudentsSideButtonPanel.setLayout(StudentsSideButtonPanelLayout);
        StudentsSideButtonPanelLayout.setHorizontalGroup(
                StudentsSideButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(StudentsSideButtonPanelLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(StudentsSideButton, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        StudentsSideButtonPanelLayout.setVerticalGroup(
                StudentsSideButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(StudentsSideButtonPanelLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(StudentsSideButton)
                                .addContainerGap(17, Short.MAX_VALUE))
        );

        AboutUsSideButtonPanel.setBackground(new java.awt.Color(255, 204, 0));


        AboutUsSideButton.setBackground(new java.awt.Color(255, 205, 0));
        AboutUsSideButton.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        AboutUsSideButton.setText("ABOUT US");
        AboutUsSideButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        AboutUsSideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutUsSideButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AboutUsSideButtonPanelLayout = new javax.swing.GroupLayout(AboutUsSideButtonPanel);
        AboutUsSideButtonPanel.setLayout(AboutUsSideButtonPanelLayout);
        AboutUsSideButtonPanelLayout.setHorizontalGroup(
                AboutUsSideButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(AboutUsSideButtonPanelLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(AboutUsSideButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AboutUsSideButtonPanelLayout.setVerticalGroup(
                AboutUsSideButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(AboutUsSideButtonPanelLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(AboutUsSideButton)
                                .addContainerGap(19, Short.MAX_VALUE))
        );

        SideBarQuizLabel.setFont(new java.awt.Font("Tw Cen MT", 3, 48)); // NOI18N
        SideBarQuizLabel.setText("QUIZ");

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N

        ExitSideButtonPanel.setBackground(new java.awt.Color(255, 204, 0));


        ExitSideButton.setBackground(new java.awt.Color(255, 205, 0));
        ExitSideButton.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        ExitSideButton.setText("EXIT");
        ExitSideButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        ExitSideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitSideButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ExitSideButtonPanelLayout = new javax.swing.GroupLayout(ExitSideButtonPanel);
        ExitSideButtonPanel.setLayout(ExitSideButtonPanelLayout);
        ExitSideButtonPanelLayout.setHorizontalGroup(
                ExitSideButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(ExitSideButtonPanelLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(ExitSideButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ExitSideButtonPanelLayout.setVerticalGroup(
                ExitSideButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(ExitSideButtonPanelLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(ExitSideButton)
                                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout sidebarLayout = new javax.swing.GroupLayout(sidebar);
        sidebar.setLayout(sidebarLayout);
        sidebarLayout.setHorizontalGroup(
                sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(HomeSideButtonPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TeachersSideButtonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(StartQuizSideButtonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(StudentsSideButtonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidebarLayout.createSequentialGroup()
                                .addContainerGap(65, Short.MAX_VALUE)
                                .addGroup(sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(sidebarLayout.createSequentialGroup()
                                                .addGap(74, 74, 74)
                                                .addComponent(SideBarQuizLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(60, 60, 60))
                        .addComponent(AboutUsSideButtonPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ExitSideButtonPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        sidebarLayout.setVerticalGroup(
                sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(sidebarLayout.createSequentialGroup()
                                .addGap(144, 144, 144)
                                .addComponent(SideBarQuizLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(138, 138, 138)
                                .addComponent(HomeSideButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(StartQuizSideButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TeachersSideButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(StudentsSideButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AboutUsSideButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ExitSideButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(160, Short.MAX_VALUE))
        );

        QuizStart.setBackground(new java.awt.Color(0, 0, 0));
        QuizStart.setBorder(javax.swing.BorderFactory.createMatteBorder(8, 0, 8, 8, new java.awt.Color(0, 0, 0)));

        WelcomeStudentLabel.setBackground(new java.awt.Color(0, 0, 0));
        WelcomeStudentLabel.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        WelcomeStudentLabel.setForeground(new java.awt.Color(255, 255, 255));
        WelcomeStudentLabel.setText("WELCOME STUDENT! THE QUIZ STARTS NOW!");

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        QuizStartTotalMarksLabel.setBackground(new java.awt.Color(0, 0, 0));
        QuizStartTotalMarksLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        QuizStartTotalMarksLabel.setForeground(new java.awt.Color(255, 204, 51));
        int totalmarks;
        if (numberofquestions=="3")
        {
            totalmarks=marksofquestions+marksofquestions+marksofquestions;
            QuizStartTotalMarksLabel.setText("TOTAL MARKS: "+ totalmarks);}
        else if (numberofquestions=="4")
        {
            totalmarks=marksofquestions+marksofquestions+marksofquestions+marksofquestions;
            QuizStartTotalMarksLabel.setText("TOTAL MARKS: "+totalmarks);}
        else if (numberofquestions=="5")
        {
            totalmarks=marksofquestions+marksofquestions+marksofquestions+marksofquestions+marksofquestions;
            QuizStartTotalMarksLabel.setText("TOTAL MARKS: "+totalmarks);}
        else if
        (numberofquestions=="6")
        {
            totalmarks=marksofquestions+marksofquestions+marksofquestions+marksofquestions+marksofquestions+marksofquestions;
            QuizStartTotalMarksLabel.setText("TOTAL MARKS: "+totalmarks);}
        else
        {
            totalmarks=marksofquestions+marksofquestions+marksofquestions+marksofquestions+marksofquestions+marksofquestions+marksofquestions;
            QuizStartTotalMarksLabel.setText("TOTAL MARKS: "+totalmarks);}

        QuizStartQ2Panel.setBackground(new java.awt.Color(0, 0, 0));

        QuizStartQ2Mcq3Label.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        QuizStartQ2Mcq3Label.setForeground(new java.awt.Color(255, 255, 255));
        QuizStartQ2Mcq3Label.setText("Q2) "+mcq3);

        Q2Mcq3ComboBox.setBackground(new java.awt.Color(255, 204, 0));
        Q2Mcq3ComboBox.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Q2Mcq3ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A) "+mcq3optA, "B) "+mcq3optB, "C) "+mcq3optC, "D) "+mcq3optD }));
        Q2Mcq3ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q2Mcq3ComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout QuizStartQ2PanelLayout = new javax.swing.GroupLayout(QuizStartQ2Panel);
        QuizStartQ2Panel.setLayout(QuizStartQ2PanelLayout);
        QuizStartQ2PanelLayout.setHorizontalGroup(
                QuizStartQ2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(QuizStartQ2PanelLayout.createSequentialGroup()
                                .addGroup(QuizStartQ2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(QuizStartQ2PanelLayout.createSequentialGroup()
                                                .addGap(14, 14, 14)
                                                .addComponent(QuizStartQ2Mcq3Label))
                                        .addGroup(QuizStartQ2PanelLayout.createSequentialGroup()
                                                .addGap(63, 63, 63)
                                                .addComponent(Q2Mcq3ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(609, Short.MAX_VALUE))
        );
        QuizStartQ2PanelLayout.setVerticalGroup(
                QuizStartQ2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(QuizStartQ2PanelLayout.createSequentialGroup()
                                .addComponent(QuizStartQ2Mcq3Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                                .addComponent(Q2Mcq3ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        QuizStartSubmitButton.setBackground(new java.awt.Color(255, 204, 0));
        QuizStartSubmitButton.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        QuizStartSubmitButton.setText("SUBMIT!");
        QuizStartSubmitButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        QuizStartSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuizStartSubmitButtonActionPerformed(evt);
            }
        });

        QuizStartQ1Panel.setBackground(new java.awt.Color(0, 0, 0));

        QuizStartQ1Mcq1Label.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        QuizStartQ1Mcq1Label.setForeground(new java.awt.Color(255, 255, 255));
        QuizStartQ1Mcq1Label.setText("Q1) "+mcq1);

        Q1Mcq1ComboBox.setBackground(new java.awt.Color(255, 204, 0));
        Q1Mcq1ComboBox.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Q1Mcq1ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A) "+mcq1optA, "B) "+mcq1optB, "C) "+mcq1optC, "D) "+mcq1optD }));
        Q1Mcq1ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q1Mcq1ComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout QuizStartQ1PanelLayout = new javax.swing.GroupLayout(QuizStartQ1Panel);
        QuizStartQ1Panel.setLayout(QuizStartQ1PanelLayout);
        QuizStartQ1PanelLayout.setHorizontalGroup(
                QuizStartQ1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(QuizStartQ1PanelLayout.createSequentialGroup()
                                .addGroup(QuizStartQ1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(QuizStartQ1PanelLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(QuizStartQ1Mcq1Label))
                                        .addGroup(QuizStartQ1PanelLayout.createSequentialGroup()
                                                .addGap(52, 52, 52)
                                                .addComponent(Q1Mcq1ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(950, Short.MAX_VALUE))
        );
        QuizStartQ1PanelLayout.setVerticalGroup(
                QuizStartQ1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(QuizStartQ1PanelLayout.createSequentialGroup()
                                .addComponent(QuizStartQ1Mcq1Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                                .addComponent(Q1Mcq1ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        QuizStartQ3Panel.setBackground(new java.awt.Color(0, 0, 0));

        QuizStartQ3Tf1Label.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        QuizStartQ3Tf1Label.setForeground(new java.awt.Color(255, 255, 255));
        QuizStartQ3Tf1Label.setText("Q3) "+tf1);

        Q3Tf1ComboBox.setBackground(new java.awt.Color(255, 204, 0));
        Q3Tf1ComboBox.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Q3Tf1ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "True", "False" }));
        Q3Tf1ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q3Tf1ComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout QuizStartQ3PanelLayout = new javax.swing.GroupLayout(QuizStartQ3Panel);
        QuizStartQ3Panel.setLayout(QuizStartQ3PanelLayout);
        QuizStartQ3PanelLayout.setHorizontalGroup(
                QuizStartQ3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(QuizStartQ3PanelLayout.createSequentialGroup()
                                .addGroup(QuizStartQ3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(QuizStartQ3PanelLayout.createSequentialGroup()
                                                .addGap(14, 14, 14)
                                                .addComponent(QuizStartQ3Tf1Label))
                                        .addGroup(QuizStartQ3PanelLayout.createSequentialGroup()
                                                .addGap(65, 65, 65)
                                                .addComponent(Q3Tf1ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(443, Short.MAX_VALUE))
        );
        QuizStartQ3PanelLayout.setVerticalGroup(
                QuizStartQ3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(QuizStartQ3PanelLayout.createSequentialGroup()
                                .addComponent(QuizStartQ3Tf1Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                                .addComponent(Q3Tf1ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        QuizStartQ4Panel.setBackground(new java.awt.Color(0, 0, 0));

        QuizStartQ4Tf3Label.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        QuizStartQ4Tf3Label.setForeground(new java.awt.Color(255, 255, 255));
        QuizStartQ4Tf3Label.setText("Q4) "+tf3);

        Q4Tf3ComboBox.setBackground(new java.awt.Color(255, 204, 0));
        Q4Tf3ComboBox.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Q4Tf3ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "True", "False" }));
        Q4Tf3ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q4Tf3ComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout QuizStartQ4PanelLayout = new javax.swing.GroupLayout(QuizStartQ4Panel);
        QuizStartQ4Panel.setLayout(QuizStartQ4PanelLayout);
        QuizStartQ4PanelLayout.setHorizontalGroup(
                QuizStartQ4PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(QuizStartQ4PanelLayout.createSequentialGroup()
                                .addGroup(QuizStartQ4PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(QuizStartQ4PanelLayout.createSequentialGroup()
                                                .addGap(15, 15, 15)
                                                .addComponent(QuizStartQ4Tf3Label))
                                        .addGroup(QuizStartQ4PanelLayout.createSequentialGroup()
                                                .addGap(62, 62, 62)
                                                .addComponent(Q4Tf3ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(417, Short.MAX_VALUE))
        );
        QuizStartQ4PanelLayout.setVerticalGroup(
                QuizStartQ4PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(QuizStartQ4PanelLayout.createSequentialGroup()
                                .addComponent(QuizStartQ4Tf3Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                                .addComponent(Q4Tf3ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        QuizStartQ5Panel.setBackground(new java.awt.Color(0, 0, 0));

        QuizStartQ5Mcq2Label.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        QuizStartQ5Mcq2Label.setForeground(new java.awt.Color(255, 255, 255));
        QuizStartQ5Mcq2Label.setText("Q5) "+mcq2);

        Q5Mcq2ComboBox.setBackground(new java.awt.Color(255, 204, 0));
        Q5Mcq2ComboBox.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Q5Mcq2ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A) "+mcq2optA, "B) "+mcq2optB, "C) "+mcq2optC, "D) "+mcq2optD }));
        Q5Mcq2ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q5Mcq2ComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout QuizStartQ5PanelLayout = new javax.swing.GroupLayout(QuizStartQ5Panel);
        QuizStartQ5Panel.setLayout(QuizStartQ5PanelLayout);
        QuizStartQ5PanelLayout.setHorizontalGroup(
                QuizStartQ5PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(QuizStartQ5PanelLayout.createSequentialGroup()
                                .addGroup(QuizStartQ5PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(QuizStartQ5PanelLayout.createSequentialGroup()
                                                .addGap(14, 14, 14)
                                                .addComponent(QuizStartQ5Mcq2Label))
                                        .addGroup(QuizStartQ5PanelLayout.createSequentialGroup()
                                                .addGap(60, 60, 60)
                                                .addComponent(Q5Mcq2ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(936, Short.MAX_VALUE))
        );
        QuizStartQ5PanelLayout.setVerticalGroup(
                QuizStartQ5PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(QuizStartQ5PanelLayout.createSequentialGroup()
                                .addComponent(QuizStartQ5Mcq2Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                                .addComponent(Q5Mcq2ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        QuizStartQ6Panel.setBackground(new java.awt.Color(0, 0, 0));

        QuizStartQ6Tf2Label.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        QuizStartQ6Tf2Label.setForeground(new java.awt.Color(255, 255, 255));
        QuizStartQ6Tf2Label.setText("Q6) "+tf2);

        Q6Tf2ComboBox.setBackground(new java.awt.Color(255, 204, 0));
        Q6Tf2ComboBox.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Q6Tf2ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "True", "False" }));
        Q6Tf2ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q6Tf2ComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout QuizStartQ6PanelLayout = new javax.swing.GroupLayout(QuizStartQ6Panel);
        QuizStartQ6Panel.setLayout(QuizStartQ6PanelLayout);
        QuizStartQ6PanelLayout.setHorizontalGroup(
                QuizStartQ6PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(QuizStartQ6PanelLayout.createSequentialGroup()
                                .addGroup(QuizStartQ6PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(QuizStartQ6PanelLayout.createSequentialGroup()
                                                .addGap(14, 14, 14)
                                                .addComponent(QuizStartQ6Tf2Label))
                                        .addGroup(QuizStartQ6PanelLayout.createSequentialGroup()
                                                .addGap(58, 58, 58)
                                                .addComponent(Q6Tf2ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(938, Short.MAX_VALUE))
        );
        QuizStartQ6PanelLayout.setVerticalGroup(
                QuizStartQ6PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, QuizStartQ6PanelLayout.createSequentialGroup()
                                .addComponent(QuizStartQ6Tf2Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                                .addComponent(Q6Tf2ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        QuizStartQ7Panel.setBackground(new java.awt.Color(0, 0, 0));

        QuizStartQ7Mcq4Label.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        QuizStartQ7Mcq4Label.setForeground(new java.awt.Color(255, 255, 255));
        QuizStartQ7Mcq4Label.setText("Q7) "+mcq4);

        Q7Mcq4ComboBox.setBackground(new java.awt.Color(255, 204, 0));
        Q7Mcq4ComboBox.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Q7Mcq4ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A) "+mcq4optA, "B) "+mcq4optB, "C) "+mcq4optC, "D) "+mcq4optD }));
        Q7Mcq4ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q7Mcq4ComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout QuizStartQ7PanelLayout = new javax.swing.GroupLayout(QuizStartQ7Panel);
        QuizStartQ7Panel.setLayout(QuizStartQ7PanelLayout);
        QuizStartQ7PanelLayout.setHorizontalGroup(
                QuizStartQ7PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(QuizStartQ7PanelLayout.createSequentialGroup()
                                .addGroup(QuizStartQ7PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(QuizStartQ7PanelLayout.createSequentialGroup()
                                                .addGap(14, 14, 14)
                                                .addComponent(QuizStartQ7Mcq4Label))
                                        .addGroup(QuizStartQ7PanelLayout.createSequentialGroup()
                                                .addGap(57, 57, 57)
                                                .addComponent(Q7Mcq4ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(934, Short.MAX_VALUE))
        );
        QuizStartQ7PanelLayout.setVerticalGroup(
                QuizStartQ7PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, QuizStartQ7PanelLayout.createSequentialGroup()
                                .addComponent(QuizStartQ7Mcq4Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                                .addComponent(Q7Mcq4ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        if (numberofquestions=="3")
        {
            QuizStartQ1Panel.setVisible(true);
            QuizStartQ2Panel.setVisible(true);
            QuizStartQ3Panel.setVisible(true);
        }
        else if (numberofquestions=="4")
        {
            QuizStartQ1Panel.setVisible(true);
            QuizStartQ2Panel.setVisible(true);
            QuizStartQ3Panel.setVisible(true);
            QuizStartQ4Panel.setVisible(true);
        }
        else if (numberofquestions=="5")
        {
            QuizStartQ1Panel.setVisible(true);
            QuizStartQ2Panel.setVisible(true);
            QuizStartQ3Panel.setVisible(true);
            QuizStartQ4Panel.setVisible(true);
            QuizStartQ5Panel.setVisible(true);
        }
        else if (numberofquestions=="6")
        {
            QuizStartQ1Panel.setVisible(true);
            QuizStartQ2Panel.setVisible(true);
            QuizStartQ3Panel.setVisible(true);
            QuizStartQ4Panel.setVisible(true);
            QuizStartQ5Panel.setVisible(true);
            QuizStartQ6Panel.setVisible(true);
        }
        else {
            QuizStartQ1Panel.setVisible(true);
            QuizStartQ2Panel.setVisible(true);
            QuizStartQ3Panel.setVisible(true);
            QuizStartQ4Panel.setVisible(true);
            QuizStartQ5Panel.setVisible(true);
            QuizStartQ6Panel.setVisible(true);
            QuizStartQ7Panel.setVisible(true);
        }

        QuizStartTimeRemainingLabel.setBackground(new java.awt.Color(0, 0, 0));
        QuizStartTimeRemainingLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N


        jSeparator15.setForeground(new java.awt.Color(255, 255, 255));

        jSeparator27.setForeground(new java.awt.Color(255, 255, 255));

        QuizStartHeader.setBackground(new java.awt.Color(255, 255, 105));

        QuizStartHeaderLabel.setBackground(new java.awt.Color(255, 255, 105));
        QuizStartHeaderLabel.setFont(new java.awt.Font("Tw Cen MT", 3, 36)); // NOI18N
        QuizStartHeaderLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        QuizStartHeaderLabel.setText("QUIZ START!");

        javax.swing.GroupLayout QuizStartHeaderLayout = new javax.swing.GroupLayout(QuizStartHeader);
        QuizStartHeader.setLayout(QuizStartHeaderLayout);
        QuizStartHeaderLayout.setHorizontalGroup(
                QuizStartHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, QuizStartHeaderLayout.createSequentialGroup()
                                .addContainerGap(616, Short.MAX_VALUE)
                                .addComponent(QuizStartHeaderLabel)
                                .addGap(586, 586, 586))
        );
        QuizStartHeaderLayout.setVerticalGroup(
                QuizStartHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(QuizStartHeaderLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(QuizStartHeaderLabel)
                                .addContainerGap(23, Short.MAX_VALUE))
        );

        AboutUsBottom1.setBackground(new java.awt.Color(255, 255, 105));

        AboutUsBottomLabel1.setFont(new java.awt.Font("Tw Cen MT", 2, 24)); // NOI18N
        AboutUsBottomLabel1.setText("© QUIZ SYSTEM CREATED BY SHAFAY. ALL RIGHTS RESERVED!");

        javax.swing.GroupLayout AboutUsBottom1Layout = new javax.swing.GroupLayout(AboutUsBottom1);
        AboutUsBottom1.setLayout(AboutUsBottom1Layout);
        AboutUsBottom1Layout.setHorizontalGroup(
                AboutUsBottom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AboutUsBottom1Layout.createSequentialGroup()
                                .addGap(383, 383, 383)
                                .addComponent(AboutUsBottomLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 930, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(309, 309, 309))
        );
        AboutUsBottom1Layout.setVerticalGroup(
                AboutUsBottom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(AboutUsBottom1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(AboutUsBottomLabel1)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout QuizStartLayout = new javax.swing.GroupLayout(QuizStart);
        QuizStart.setLayout(QuizStartLayout);
        QuizStartLayout.setHorizontalGroup(
                QuizStartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(QuizStartLayout.createSequentialGroup()
                                .addComponent(QuizStartHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(QuizStartLayout.createSequentialGroup()
                                .addGroup(QuizStartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(AboutUsBottom1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(QuizStartLayout.createSequentialGroup()
                                                .addGroup(QuizStartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(QuizStartLayout.createSequentialGroup()
                                                                .addGap(16, 16, 16)
                                                                .addGroup(QuizStartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(QuizStartQ1Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGroup(QuizStartLayout.createSequentialGroup()
                                                                                .addGroup(QuizStartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                                        .addComponent(jSeparator27, javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(QuizStartTotalMarksLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                                                .addGap(93, 93, 93)
                                                                                .addGroup(QuizStartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(WelcomeStudentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 695, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGap(66, 66, 66)
                                                                                .addGroup(QuizStartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(jSeparator15, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addComponent(QuizStartTimeRemainingLabel)))))
                                                        .addGroup(QuizStartLayout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(QuizStartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(QuizStartQ2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(QuizStartQ3Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(QuizStartQ4Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addGroup(QuizStartLayout.createSequentialGroup()
                                                                .addGap(612, 612, 612)
                                                                .addComponent(QuizStartSubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
                        .addGroup(QuizStartLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(QuizStartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(QuizStartQ7Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(QuizStartQ6Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(QuizStartQ5Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        QuizStartLayout.setVerticalGroup(
                QuizStartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, QuizStartLayout.createSequentialGroup()
                                .addGroup(QuizStartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(QuizStartLayout.createSequentialGroup()
                                                .addComponent(QuizStartHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(QuizStartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(WelcomeStudentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(QuizStartTotalMarksLabel)
                                                        .addComponent(QuizStartTimeRemainingLabel))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(QuizStartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jSeparator15, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(jSeparator27, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(QuizStartQ1Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(QuizStartQ2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(QuizStartQ3Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(QuizStartQ4Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(QuizStartQ5Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(QuizStartQ6Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(QuizStartQ7Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(QuizStartSubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(AboutUsBottom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(sidebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(QuizStart, javax.swing.GroupLayout.PREFERRED_SIZE, 1373, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(sidebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                        .addComponent(QuizStart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>

    private void HomeSideButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        new homepage().setVisible(true);
        setVisible(false);
    }


    private void StartQuizSideButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:

        new QuizRegistration().setVisible(true);
        setVisible(false);
    }


    private void TeachersSideButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here
        new TeachersData().setVisible(true);
        setVisible(false);
    }


    private void StudentsSideButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        new StudentsData().setVisible(true);
        setVisible(false);
    }


    private void AboutUsSideButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling
        new AboutUs().setVisible(true);
        setVisible(false);

    }


    private void ExitSideButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:

        setVisible(false);
    }


    private void QuizStartSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:

        Q1StudentAnswer= String.valueOf(Q1Mcq1ComboBox.getSelectedItem());
        Q2StudentAnswer= String.valueOf(Q2Mcq3ComboBox.getSelectedItem());
        Q3StudentAnswer= String.valueOf(Q3Tf1ComboBox.getSelectedItem());
        Q4StudentAnswer= String.valueOf(Q4Tf3ComboBox.getSelectedItem());
        Q5StudentAnswer= String.valueOf(Q5Mcq2ComboBox.getSelectedItem());
        Q6StudentAnswer= String.valueOf(Q6Tf2ComboBox.getSelectedItem());
        Q7StudentAnswer= String.valueOf(Q7Mcq4ComboBox.getSelectedItem());
        new QuizAnswerKey(Q1StudentAnswer,Q2StudentAnswer,Q3StudentAnswer,Q4StudentAnswer,Q5StudentAnswer,Q6StudentAnswer,Q7StudentAnswer,CourseTopic1,numberofquestions,marksofquestions,day,month,year,hour,minute,mcq1,mcq1optA,mcq1optB,mcq1optC,mcq1optD,mcq1Correctopt,mcq2,mcq2optA,mcq2optB,mcq2optC,mcq2optD,mcq2Correctopt,mcq3,mcq3optA,mcq3optB,mcq3optC,mcq3optD,mcq3Correctopt,mcq4,mcq4optA,mcq4optB,mcq4optC,mcq4optD,mcq4Correctopt,tf1,tf1Correctopt,tf2,tf2Correctopt,tf3,tf3Correctopt,teacher,student,selectedCourse).setVisible(true);
        setVisible(false);
    }

    private void Q1Mcq1ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void Q2Mcq3ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void Q3Tf1ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void Q4Tf3ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void Q5Mcq2ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void Q6Tf2ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void Q7Mcq4ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuizStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuizStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuizStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuizStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */

    }

    // Variables declaration - do not modify
    public String Q1StudentAnswer;
    public String Q2StudentAnswer;
    public String Q3StudentAnswer;
    public String Q4StudentAnswer;
    public String  Q5StudentAnswer;
    public String Q6StudentAnswer;
    public String Q7StudentAnswer;
    private javax.swing.JPanel AboutUsBottom1;
    private javax.swing.JLabel AboutUsBottomLabel1;
    private javax.swing.JButton AboutUsSideButton;
    private javax.swing.JPanel AboutUsSideButtonPanel;
    private javax.swing.JButton ExitSideButton;
    private javax.swing.JPanel ExitSideButtonPanel;
    private javax.swing.JButton HomeSideButton;
    private javax.swing.JPanel HomeSideButtonPanel;
    public static javax.swing.JComboBox<String> Q1Mcq1ComboBox;
    public static javax.swing.JComboBox<String> Q2Mcq3ComboBox;
    public static javax.swing.JComboBox<String> Q3Tf1ComboBox;
    public static javax.swing.JComboBox<String> Q4Tf3ComboBox;
    public static javax.swing.JComboBox<String> Q5Mcq2ComboBox;
    public static javax.swing.JComboBox<String> Q6Tf2ComboBox;
    public static javax.swing.JComboBox<String> Q7Mcq4ComboBox;
    private javax.swing.JPanel QuizStart;
    private javax.swing.JPanel QuizStartHeader;
    private javax.swing.JLabel QuizStartHeaderLabel;
    private javax.swing.JLabel QuizStartQ1Mcq1Label;
    private javax.swing.JPanel QuizStartQ1Panel;
    private javax.swing.JLabel QuizStartQ2Mcq3Label;
    private javax.swing.JPanel QuizStartQ2Panel;
    private javax.swing.JPanel QuizStartQ3Panel;
    private javax.swing.JLabel QuizStartQ3Tf1Label;
    private javax.swing.JPanel QuizStartQ4Panel;
    private javax.swing.JLabel QuizStartQ4Tf3Label;
    private javax.swing.JLabel QuizStartQ5Mcq2Label;
    private javax.swing.JPanel QuizStartQ5Panel;
    private javax.swing.JPanel QuizStartQ6Panel;
    private javax.swing.JLabel QuizStartQ6Tf2Label;
    private javax.swing.JLabel QuizStartQ7Mcq4Label;
    private javax.swing.JPanel QuizStartQ7Panel;
    private javax.swing.JButton QuizStartSubmitButton;
    private javax.swing.JLabel QuizStartTimeRemainingLabel;
    private javax.swing.JLabel QuizStartTotalMarksLabel;
    private javax.swing.JLabel SideBarQuizLabel;
    private javax.swing.JButton StartQuizSideButton;
    private javax.swing.JPanel StartQuizSideButtonPanel;
    private javax.swing.JButton StudentsSideButton;
    private javax.swing.JPanel StudentsSideButtonPanel;
    private javax.swing.JButton TeachersSideButton;
    private javax.swing.JPanel TeachersSideButtonPanel;
    private javax.swing.JLabel WelcomeStudentLabel;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator27;
    private javax.swing.JPanel sidebar;
    // End of variables declaration
}
