
package com.mycompany.projectguitrying;

import javax.swing.*;
import java.util.Arrays;

/**
 *
 * @author SHAFAY
 */
public class QuizSetting extends javax.swing.JFrame {

    /**
     * Creates new form QuizSetting
     */
    String mcq1;
    String mcq1optA;
    String mcq1optB;
    String mcq1optC;
    String mcq1optD;
    String mcq1Correctopt;
    String mcq2;
    String mcq2optA;
    String mcq2optB;
    String mcq2optC;
    String mcq2optD;
    String mcq2Correctopt;
    String mcq3;
    String mcq3optA;
    String mcq3optB;
    String mcq3optC;
    String mcq3optD;
    String mcq3Correctopt;
    String mcq4;
    String mcq4optA;
    String mcq4optB;
    String mcq4optC;
    String mcq4optD;
    String mcq4Correctopt;
    String tf1;
    String tf1Correctopt;
    String tf2;
    String tf2Correctopt;
    String tf3;
    String tf3Correctopt;
    String teacher;
    String student;
    String selectedCourse;
    public String numberofquestions;
    public String marksofquestions;
    public String day;
    public String month;
    public String year;
    public String hour;
    public String minute;
    public String CourseTopic1;

    public QuizSetting(String mcq1, String mcq1optA, String mcq1optB, String mcq1optC, String mcq1optD, String mcq1Correctopt, String mcq2, String mcq2optA, String mcq2optB, String mcq2optC, String mcq2optD, String mcq2Correctopt, String mcq3, String mcq3optA, String mcq3optB, String mcq3optC, String mcq3optD, String mcq3Correctopt, String mcq4, String mcq4optA, String mcq4optB, String mcq4optC, String mcq4optD, String mcq4Correctopt, String tf1, String tf1Correctopt, String tf2, String tf2Correctopt, String tf3, String tf3Correctopt, String teacher, String student, String selectedCourse) {

        this.mcq1=mcq1;
        this.mcq1optA=mcq1optA;
        this.mcq1optB=mcq1optB;
        this.mcq1optC=mcq1optC;
        this.mcq1optD=mcq1optD;
        this.mcq1Correctopt=mcq1Correctopt;
        this.mcq2=mcq2;
        this.mcq2optA=mcq2optA;
        this.mcq2optB=mcq2optB;
        this.mcq2optC=mcq2optC;
        this.mcq2optD=mcq2optD;
        this.mcq2Correctopt=mcq2Correctopt;
        this.mcq3=mcq3;
        this.mcq3optA=mcq3optA;
        this.mcq3optB=mcq3optB;
        this.mcq3optC=mcq3optC;
        this.mcq3optD=mcq3optD;
        this.mcq3Correctopt=mcq3Correctopt;
        this.mcq4=mcq4;
        this.mcq4optA=mcq4optA;
        this.mcq4optB=mcq4optB;
        this.mcq4optC=mcq4optC;
        this.mcq4optD=mcq4optD;
        this.mcq4Correctopt=mcq4Correctopt;
        this.tf1=tf1;
        this.tf1Correctopt=tf1Correctopt;
        this.tf2=tf2;
        this.tf2Correctopt=tf2Correctopt;
        this.tf3=tf3;
        this.tf3Correctopt=tf3Correctopt;
        this.teacher=teacher;
        this.student=student;
        this.selectedCourse=selectedCourse;
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        sidebar = new javax.swing.JPanel();
        HomeSideButtonPanel = new javax.swing.JPanel();
        HomeSideButton = new javax.swing.JButton();
        StartQuizSideButtonPanel = new javax.swing.JPanel();
        StartQuizSideButton = new javax.swing.JButton();
        TeachersSideButtonPanel = new javax.swing.JPanel();
        TeachersSideButton = new javax.swing.JButton();
        StudentsSideButtonPanel = new javax.swing.JPanel();
        StudentsSideButton = new javax.swing.JButton();
        AboutUsSideButtonPanel = new javax.swing.JPanel();
        AboutUsSideButton = new javax.swing.JButton();
        SideBarQuizLabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        ExitSideButtonPanel = new javax.swing.JPanel();
        ExitSideButton = new javax.swing.JButton();
        QuizSetting = new javax.swing.JPanel();
        QuizSettingBottom = new javax.swing.JPanel();
        QuizSettingBottomLabel = new javax.swing.JLabel();
        QuizSettingHeader = new javax.swing.JPanel();
        QuizSettingHeaderLabel = new javax.swing.JLabel();
        PleaseSelectTopicLabel = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        PleaseChooseNumberOfQuestionsLabel = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        PleaseChooseNumberOfQuestionsComboBox = new javax.swing.JComboBox<>();
        PleaseChooseMarksOfQuestionsLabel = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        PleaseChooseMarksOfQuestionsComboBox = new javax.swing.JComboBox<>();
        PleaseChooseDateTimeLabel = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        DayLabel = new javax.swing.JLabel();
        YearLabel = new javax.swing.JLabel();
        MonthLabel = new javax.swing.JLabel();
        HourLabel = new javax.swing.JLabel();
        MinuteLabel = new javax.swing.JLabel();
        MonthTextField = new javax.swing.JTextField();
        YearTextField = new javax.swing.JTextField();
        DayTextField = new javax.swing.JTextField();
        HourTextField = new javax.swing.JTextField();
        MinuteTextField = new javax.swing.JTextField();
        QuizSettingNextButton = new javax.swing.JButton();
        PleaseChooseTopicComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sidebar.setBackground(new java.awt.Color(255, 255, 105));
        sidebar.setBorder(javax.swing.BorderFactory.createMatteBorder(8, 8, 8, 8, new java.awt.Color(0, 0, 0)));

        HomeSideButtonPanel.setBackground(new java.awt.Color(255, 204, 0));


        HomeSideButton.setBackground(new java.awt.Color(255, 204, 0));
        HomeSideButton.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        HomeSideButton.setText("HOME");
        HomeSideButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        HomeSideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeSideButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout HomeSideButtonPanelLayout = new javax.swing.GroupLayout(HomeSideButtonPanel);
        HomeSideButtonPanel.setLayout(HomeSideButtonPanelLayout);
        HomeSideButtonPanelLayout.setHorizontalGroup(
                HomeSideButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(HomeSideButtonPanelLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(HomeSideButton, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );
        HomeSideButtonPanelLayout.setVerticalGroup(
                HomeSideButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomeSideButtonPanelLayout.createSequentialGroup()
                                .addContainerGap(11, Short.MAX_VALUE)
                                .addComponent(HomeSideButton)
                                .addGap(15, 15, 15))
        );

        StartQuizSideButtonPanel.setBackground(new java.awt.Color(255, 204, 0));


        StartQuizSideButton.setBackground(new java.awt.Color(255, 205, 0));
        StartQuizSideButton.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        StartQuizSideButton.setText("START QUIZ");
        StartQuizSideButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        StartQuizSideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartQuizSideButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout StartQuizSideButtonPanelLayout = new javax.swing.GroupLayout(StartQuizSideButtonPanel);
        StartQuizSideButtonPanel.setLayout(StartQuizSideButtonPanelLayout);
        StartQuizSideButtonPanelLayout.setHorizontalGroup(
                StartQuizSideButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(StartQuizSideButtonPanelLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(StartQuizSideButton, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        StartQuizSideButtonPanelLayout.setVerticalGroup(
                StartQuizSideButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(StartQuizSideButtonPanelLayout.createSequentialGroup()
                                .addContainerGap(14, Short.MAX_VALUE)
                                .addComponent(StartQuizSideButton)
                                .addGap(14, 14, 14))
        );

        TeachersSideButtonPanel.setBackground(new java.awt.Color(255, 204, 0));


        TeachersSideButton.setBackground(new java.awt.Color(255, 205, 0));
        TeachersSideButton.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        TeachersSideButton.setText("TEACHERS");
        TeachersSideButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        TeachersSideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeachersSideButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TeachersSideButtonPanelLayout = new javax.swing.GroupLayout(TeachersSideButtonPanel);
        TeachersSideButtonPanel.setLayout(TeachersSideButtonPanelLayout);
        TeachersSideButtonPanelLayout.setHorizontalGroup(
                TeachersSideButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(TeachersSideButtonPanelLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(TeachersSideButton, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TeachersSideButtonPanelLayout.setVerticalGroup(
                TeachersSideButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(TeachersSideButtonPanelLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(TeachersSideButton)
                                .addContainerGap(15, Short.MAX_VALUE))
        );

        StudentsSideButtonPanel.setBackground(new java.awt.Color(255, 204, 0));


        StudentsSideButton.setBackground(new java.awt.Color(255, 205, 0));
        StudentsSideButton.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        StudentsSideButton.setText("STUDENTS");
        StudentsSideButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        StudentsSideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentsSideButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout StudentsSideButtonPanelLayout = new javax.swing.GroupLayout(StudentsSideButtonPanel);
        StudentsSideButtonPanel.setLayout(StudentsSideButtonPanelLayout);
        StudentsSideButtonPanelLayout.setHorizontalGroup(
                StudentsSideButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(StudentsSideButtonPanelLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(StudentsSideButton, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        StudentsSideButtonPanelLayout.setVerticalGroup(
                StudentsSideButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(StudentsSideButtonPanelLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(StudentsSideButton)
                                .addContainerGap(17, Short.MAX_VALUE))
        );

        AboutUsSideButtonPanel.setBackground(new java.awt.Color(255, 204, 0));


        AboutUsSideButton.setBackground(new java.awt.Color(255, 205, 0));
        AboutUsSideButton.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        AboutUsSideButton.setText("ABOUT US");
        AboutUsSideButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        AboutUsSideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutUsSideButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AboutUsSideButtonPanelLayout = new javax.swing.GroupLayout(AboutUsSideButtonPanel);
        AboutUsSideButtonPanel.setLayout(AboutUsSideButtonPanelLayout);
        AboutUsSideButtonPanelLayout.setHorizontalGroup(
                AboutUsSideButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(AboutUsSideButtonPanelLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(AboutUsSideButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AboutUsSideButtonPanelLayout.setVerticalGroup(
                AboutUsSideButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(AboutUsSideButtonPanelLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(AboutUsSideButton)
                                .addContainerGap(19, Short.MAX_VALUE))
        );

        SideBarQuizLabel.setFont(new java.awt.Font("Tw Cen MT", 3, 48)); // NOI18N
        SideBarQuizLabel.setText("QUIZ");

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N

        ExitSideButtonPanel.setBackground(new java.awt.Color(255, 204, 0));


        ExitSideButton.setBackground(new java.awt.Color(255, 205, 0));
        ExitSideButton.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        ExitSideButton.setText("EXIT");
        ExitSideButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        ExitSideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitSideButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ExitSideButtonPanelLayout = new javax.swing.GroupLayout(ExitSideButtonPanel);
        ExitSideButtonPanel.setLayout(ExitSideButtonPanelLayout);
        ExitSideButtonPanelLayout.setHorizontalGroup(
                ExitSideButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(ExitSideButtonPanelLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(ExitSideButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ExitSideButtonPanelLayout.setVerticalGroup(
                ExitSideButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(ExitSideButtonPanelLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(ExitSideButton)
                                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout sidebarLayout = new javax.swing.GroupLayout(sidebar);
        sidebar.setLayout(sidebarLayout);
        sidebarLayout.setHorizontalGroup(
                sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(HomeSideButtonPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TeachersSideButtonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(StartQuizSideButtonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(StudentsSideButtonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidebarLayout.createSequentialGroup()
                                .addContainerGap(65, Short.MAX_VALUE)
                                .addGroup(sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(sidebarLayout.createSequentialGroup()
                                                .addGap(74, 74, 74)
                                                .addComponent(SideBarQuizLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(60, 60, 60))
                        .addComponent(AboutUsSideButtonPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ExitSideButtonPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        sidebarLayout.setVerticalGroup(
                sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(sidebarLayout.createSequentialGroup()
                                .addGap(144, 144, 144)
                                .addComponent(SideBarQuizLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(138, 138, 138)
                                .addComponent(HomeSideButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(StartQuizSideButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TeachersSideButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(StudentsSideButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AboutUsSideButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ExitSideButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(160, Short.MAX_VALUE))
        );

        QuizSetting.setBackground(new java.awt.Color(0, 0, 0));
        QuizSetting.setBorder(javax.swing.BorderFactory.createMatteBorder(8, 0, 8, 8, new java.awt.Color(0, 0, 0)));

        QuizSettingBottom.setBackground(new java.awt.Color(255, 255, 105));

        QuizSettingBottomLabel.setFont(new java.awt.Font("Tw Cen MT", 2, 24)); // NOI18N
        QuizSettingBottomLabel.setText("© QUIZ SYSTEM CREATED BY SHAFAY. ALL RIGHTS RESERVED!");

        javax.swing.GroupLayout QuizSettingBottomLayout = new javax.swing.GroupLayout(QuizSettingBottom);
        QuizSettingBottom.setLayout(QuizSettingBottomLayout);
        QuizSettingBottomLayout.setHorizontalGroup(
                QuizSettingBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, QuizSettingBottomLayout.createSequentialGroup()
                                .addGap(383, 383, 383)
                                .addComponent(QuizSettingBottomLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 930, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(66, 66, 66))
        );
        QuizSettingBottomLayout.setVerticalGroup(
                QuizSettingBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(QuizSettingBottomLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(QuizSettingBottomLabel)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        QuizSettingHeader.setBackground(new java.awt.Color(255, 255, 105));

        QuizSettingHeaderLabel.setBackground(new java.awt.Color(255, 255, 105));
        QuizSettingHeaderLabel.setFont(new java.awt.Font("Tw Cen MT", 3, 36)); // NOI18N
        QuizSettingHeaderLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        QuizSettingHeaderLabel.setText("QUIZ SETTING!");

        javax.swing.GroupLayout QuizSettingHeaderLayout = new javax.swing.GroupLayout(QuizSettingHeader);
        QuizSettingHeader.setLayout(QuizSettingHeaderLayout);
        QuizSettingHeaderLayout.setHorizontalGroup(
                QuizSettingHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, QuizSettingHeaderLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(QuizSettingHeaderLabel)
                                .addGap(576, 576, 576))
        );
        QuizSettingHeaderLayout.setVerticalGroup(
                QuizSettingHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(QuizSettingHeaderLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(QuizSettingHeaderLabel)
                                .addContainerGap(25, Short.MAX_VALUE))
        );

        PleaseSelectTopicLabel.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        PleaseSelectTopicLabel.setForeground(new java.awt.Color(255, 255, 255));
        PleaseSelectTopicLabel.setText("Please select the topic for the quiz: "+selectedCourse);

        jSeparator8.setForeground(new java.awt.Color(255, 255, 255));

        PleaseChooseNumberOfQuestionsLabel.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        PleaseChooseNumberOfQuestionsLabel.setForeground(new java.awt.Color(255, 255, 255));
        PleaseChooseNumberOfQuestionsLabel.setText("Please choose the number of questions for the quiz:");

        jSeparator9.setForeground(new java.awt.Color(255, 255, 255));

        PleaseChooseNumberOfQuestionsComboBox.setBackground(new java.awt.Color(255, 204, 0));
        PleaseChooseNumberOfQuestionsComboBox.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        PleaseChooseNumberOfQuestionsComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3 QUESTIONS", "4 QUESTIONS", "5 QUESTIONS", "6 QUESTIONS", "7 QUESTIONS" }));
        PleaseChooseNumberOfQuestionsComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PleaseChooseNumberOfQuestionsComboBoxActionPerformed(evt);
            }
        });

        PleaseChooseMarksOfQuestionsLabel.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        PleaseChooseMarksOfQuestionsLabel.setForeground(new java.awt.Color(255, 255, 255));
        PleaseChooseMarksOfQuestionsLabel.setText("Please choose the marks of each question for the quiz:");

        jSeparator10.setForeground(new java.awt.Color(255, 255, 255));

        PleaseChooseMarksOfQuestionsComboBox.setBackground(new java.awt.Color(255, 204, 0));
        PleaseChooseMarksOfQuestionsComboBox.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        PleaseChooseMarksOfQuestionsComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "10", "15", "20" }));
        PleaseChooseMarksOfQuestionsComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PleaseChooseMarksOfQuestionsComboBoxActionPerformed(evt);
            }
        });

        PleaseChooseDateTimeLabel.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        PleaseChooseDateTimeLabel.setForeground(new java.awt.Color(255, 255, 255));
        PleaseChooseDateTimeLabel.setText("Please choose the date and time for the quiz:");

        jSeparator11.setForeground(new java.awt.Color(255, 255, 255));

        DayLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        DayLabel.setForeground(new java.awt.Color(255, 255, 255));
        DayLabel.setText("DAY:");

        YearLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        YearLabel.setForeground(new java.awt.Color(255, 255, 255));
        YearLabel.setText("YEAR:");

        MonthLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        MonthLabel.setForeground(new java.awt.Color(255, 255, 255));
        MonthLabel.setText("MONTH:");

        HourLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        HourLabel.setForeground(new java.awt.Color(255, 255, 255));
        HourLabel.setText("HOUR:");

        MinuteLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        MinuteLabel.setForeground(new java.awt.Color(255, 255, 255));
        MinuteLabel.setText("MINUTE:");

        MonthTextField.setBackground(new java.awt.Color(255, 204, 0));
        MonthTextField.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        MonthTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        MonthTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MonthTextFieldActionPerformed(evt);
            }
        });

        YearTextField.setBackground(new java.awt.Color(255, 204, 0));
        YearTextField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        YearTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        YearTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YearTextFieldActionPerformed(evt);
            }
        });

        DayTextField.setBackground(new java.awt.Color(255, 204, 0));
        DayTextField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DayTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        DayTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DayTextFieldActionPerformed(evt);
            }
        });

        HourTextField.setBackground(new java.awt.Color(255, 204, 0));
        HourTextField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        HourTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        HourTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HourTextFieldActionPerformed(evt);
            }
        });

        MinuteTextField.setBackground(new java.awt.Color(255, 204, 0));
        MinuteTextField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MinuteTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        MinuteTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinuteTextFieldActionPerformed(evt);
            }
        });

        QuizSettingNextButton.setBackground(new java.awt.Color(255, 204, 0));
        QuizSettingNextButton.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        QuizSettingNextButton.setText("NEXT!");
        QuizSettingNextButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        QuizSettingNextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuizSettingNextButtonActionPerformed(evt);
            }
        });

        PleaseChooseTopicComboBox.setBackground(new java.awt.Color(255, 204, 0));
        PleaseChooseTopicComboBox.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        PleaseChooseTopicComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "topic1 here", "topic2 here" }));
        PleaseChooseTopicComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PleaseChooseTopicComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout QuizSettingLayout = new javax.swing.GroupLayout(QuizSetting);
        QuizSetting.setLayout(QuizSettingLayout);
        QuizSettingLayout.setHorizontalGroup(
                QuizSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(QuizSettingHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(QuizSettingBottom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(QuizSettingLayout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addGroup(QuizSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(PleaseSelectTopicLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(PleaseChooseDateTimeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(PleaseChooseNumberOfQuestionsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(PleaseChooseMarksOfQuestionsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(QuizSettingLayout.createSequentialGroup()
                                                .addGroup(QuizSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 851, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(PleaseChooseTopicComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 824, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(PleaseChooseNumberOfQuestionsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(PleaseChooseMarksOfQuestionsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 864, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 715, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(QuizSettingLayout.createSequentialGroup()
                                                                .addGroup(QuizSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(QuizSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(DayLabel)
                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, QuizSettingLayout.createSequentialGroup()
                                                                                        .addGap(2, 2, 2)
                                                                                        .addComponent(MonthLabel)))
                                                                        .addGroup(QuizSettingLayout.createSequentialGroup()
                                                                                .addGap(2, 2, 2)
                                                                                .addGroup(QuizSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(HourLabel)
                                                                                        .addComponent(YearLabel)
                                                                                        .addComponent(MinuteLabel))))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(QuizSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(YearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(HourTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(DayTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(MonthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGroup(QuizSettingLayout.createSequentialGroup()
                                                                                .addComponent(MinuteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(287, 287, 287)
                                                                                .addComponent(QuizSettingNextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
        );
        QuizSettingLayout.setVerticalGroup(
                QuizSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, QuizSettingLayout.createSequentialGroup()
                                .addComponent(QuizSettingHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(PleaseSelectTopicLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(PleaseChooseTopicComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(PleaseChooseNumberOfQuestionsLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PleaseChooseNumberOfQuestionsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PleaseChooseMarksOfQuestionsLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PleaseChooseMarksOfQuestionsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(PleaseChooseDateTimeLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(QuizSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(DayLabel)
                                        .addComponent(DayTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(QuizSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(MonthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(MonthLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(QuizSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(YearLabel)
                                        .addComponent(YearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(QuizSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(HourLabel)
                                        .addComponent(HourTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(QuizSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(QuizSettingLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(QuizSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(MinuteLabel)
                                                        .addComponent(MinuteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(QuizSettingLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                                                .addComponent(QuizSettingNextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(48, 48, 48)))
                                .addComponent(QuizSettingBottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(sidebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(QuizSetting, javax.swing.GroupLayout.PREFERRED_SIZE, 1373, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(sidebar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(QuizSetting, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void HomeSideButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        new homepage().setVisible(true);
        setVisible(false);
    }


    private void StartQuizSideButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        new QuizRegistration().setVisible(true);
        setVisible(false);
    }


    private void TeachersSideButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here
        new TeachersData().setVisible(true);
        setVisible(false);
    }


    private void StudentsSideButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        new StudentsData().setVisible(true);
        setVisible(false);
    }


    private void AboutUsSideButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling
        new AboutUs().setVisible(true);
        setVisible(false);

    }


    private void ExitSideButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:

        setVisible(false);
    }


    private void PleaseChooseNumberOfQuestionsComboBoxActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void PleaseChooseMarksOfQuestionsComboBoxActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void MonthTextFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void YearTextFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void DayTextFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void HourTextFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void MinuteTextFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void QuizSettingNextButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        numberofquestions = PleaseChooseNumberOfQuestionsComboBox.getSelectedItem().toString();
        marksofquestions = PleaseChooseMarksOfQuestionsComboBox.getSelectedItem().toString();
        day = DayTextField.getText();
        month = MonthTextField.getText();
        year = YearTextField.getText();
        hour = HourTextField.getText();
        minute = MinuteTextField.getText();
        CourseTopic1= String.valueOf(PleaseChooseTopicComboBox.getSelectedItem());

        new QuizStart(CourseTopic1,numberofquestions,marksofquestions,day,month,year,hour,minute,mcq1,mcq1optA,mcq1optB,mcq1optC,mcq1optD,mcq1Correctopt,mcq2,mcq2optA,mcq2optB,mcq2optC,mcq2optD,mcq2Correctopt,mcq3,mcq3optA,mcq3optB,mcq3optC,mcq3optD,mcq3Correctopt,mcq4,mcq4optA,mcq4optB,mcq4optC,mcq4optD,mcq4Correctopt,tf1,tf1Correctopt,tf2,tf2Correctopt,tf3,tf3Correctopt,teacher,student,selectedCourse).setVisible(true);
        setVisible(false);
    }

    private void PleaseChooseTopicComboBoxActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuizSetting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuizSetting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuizSetting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuizSetting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        QuizRegistration reg= new QuizRegistration();
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton AboutUsSideButton;
    private javax.swing.JPanel AboutUsSideButtonPanel;
    private javax.swing.JLabel DayLabel;
    private javax.swing.JTextField DayTextField;
    private javax.swing.JButton ExitSideButton;
    private javax.swing.JPanel ExitSideButtonPanel;
    private javax.swing.JButton HomeSideButton;
    private javax.swing.JPanel HomeSideButtonPanel;
    private javax.swing.JLabel HourLabel;
    private javax.swing.JTextField HourTextField;
    private javax.swing.JLabel MinuteLabel;
    private javax.swing.JTextField MinuteTextField;
    private javax.swing.JLabel MonthLabel;
    private javax.swing.JTextField MonthTextField;
    private javax.swing.JLabel PleaseChooseDateTimeLabel;
    private javax.swing.JComboBox<String> PleaseChooseMarksOfQuestionsComboBox;
    private javax.swing.JLabel PleaseChooseMarksOfQuestionsLabel;
    private javax.swing.JComboBox<String> PleaseChooseNumberOfQuestionsComboBox;
    private javax.swing.JLabel PleaseChooseNumberOfQuestionsLabel;
    private javax.swing.JComboBox<String> PleaseChooseTopicComboBox;
    private javax.swing.JLabel PleaseSelectTopicLabel;
    private javax.swing.JPanel QuizSetting;
    private javax.swing.JPanel QuizSettingBottom;
    private javax.swing.JLabel QuizSettingBottomLabel;
    private javax.swing.JPanel QuizSettingHeader;
    private javax.swing.JLabel QuizSettingHeaderLabel;
    private javax.swing.JButton QuizSettingNextButton;
    private javax.swing.JLabel SideBarQuizLabel;
    private javax.swing.JButton StartQuizSideButton;
    private javax.swing.JPanel StartQuizSideButtonPanel;
    private javax.swing.JButton StudentsSideButton;
    private javax.swing.JPanel StudentsSideButtonPanel;
    private javax.swing.JButton TeachersSideButton;
    private javax.swing.JPanel TeachersSideButtonPanel;
    private javax.swing.JLabel YearLabel;
    private javax.swing.JTextField YearTextField;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JPanel sidebar;
    // End of variables declaration                   
}
