
package com.mycompany.projectguitrying;

/**
 *
 * @author SHAFAY
 */
public class QuizMarksheet extends javax.swing.JFrame {

    /**
     * Creates new form QuizMarksheet
     */
    String q1StudentAnswer;
    String q2StudentAnswer;
    String q3StudentAnswer;
    String q4StudentAnswer;
    String q5StudentAnswer;
    String q6StudentAnswer;
    String q7StudentAnswer;
    String numberofquestions;
    int marksofquestions;
    String day;
    String month;
    String year;
    String hour;
    String minute;
    String mcq1;
    String mcq1optA;
    String mcq1optB;
    String mcq1optC;
    String mcq1optD;
    String mcq1Correctopt;
    String mcq2;
    String mcq2optA;
    String mcq2optB;
    String mcq2optC;
    String mcq2optD;
    String mcq2Correctopt;
    String mcq3;
    String mcq3optA;
    String mcq3optB;
    String mcq3optC;
    String mcq3optD;
    String mcq3Correctopt;
    String mcq4;
    String mcq4optA;
    String mcq4optB;
    String mcq4optC;
    String mcq4optD;
    String mcq4Correctopt;
    String tf1;
    String tf1Correctopt;
    String tf2;
    String tf2Correctopt;
    String tf3;
    String tf3Correctopt;
    String teacher;
    String student;
    String selectedCourse;
    String CourseTopic1;

    public QuizMarksheet(String q1StudentAnswer, String q2StudentAnswer, String q3StudentAnswer, String q4StudentAnswer, String q5StudentAnswer, String q6StudentAnswer, String q7StudentAnswer, String courseTopic1, String numberofquestions, int marksofquestions, String day, String month, String year, String hour, String minute, String mcq1, String mcq1optA, String mcq1optB, String mcq1optC, String mcq1optD, String mcq1Correctopt, String mcq2, String mcq2optA, String mcq2optB, String mcq2optC, String mcq2optD, String mcq2Correctopt, String mcq3, String mcq3optA, String mcq3optB, String mcq3optC, String mcq3optD, String mcq3Correctopt, String mcq4, String mcq4optA, String mcq4optB, String mcq4optC, String mcq4optD, String mcq4Correctopt, String tf1, String tf1Correctopt, String tf2, String tf2Correctopt, String tf3, String tf3Correctopt, String teacher, String student, String selectedCourse) {
        this.CourseTopic1=CourseTopic1;
        this.q1StudentAnswer=q1StudentAnswer;
        this.q2StudentAnswer=q2StudentAnswer;
        this.q3StudentAnswer=q3StudentAnswer;
        this.q4StudentAnswer=q4StudentAnswer;
        this.q5StudentAnswer=q5StudentAnswer;
        this.q6StudentAnswer=q6StudentAnswer;
        this.q7StudentAnswer=q7StudentAnswer;
        this.mcq1=mcq1;
        this.mcq1optA=mcq1optA;
        this.mcq1optB=mcq1optB;
        this.mcq1optC=mcq1optC;
        this.mcq1optD=mcq1optD;
        this.mcq1Correctopt=mcq1Correctopt;
        this.mcq2=mcq2;
        this.mcq2optA=mcq2optA;
        this.mcq2optB=mcq2optB;
        this.mcq2optC=mcq2optC;
        this.mcq2optD=mcq2optD;
        this.mcq2Correctopt=mcq2Correctopt;
        this.mcq3=mcq3;
        this.mcq3optA=mcq3optA;
        this.mcq3optB=mcq3optB;
        this.mcq3optC=mcq3optC;
        this.mcq3optD=mcq3optD;
        this.mcq3Correctopt=mcq3Correctopt;
        this.mcq4=mcq4;
        this.mcq4optA=mcq4optA;
        this.mcq4optB=mcq4optB;
        this.mcq4optC=mcq4optC;
        this.mcq4optD=mcq4optD;
        this.mcq4Correctopt=mcq4Correctopt;
        this.tf1=tf1;
        this.tf1Correctopt=tf1Correctopt;
        this.tf2=tf2;
        this.tf2Correctopt=tf2Correctopt;
        this.tf3=tf3;
        this.tf3Correctopt=tf3Correctopt;
        this.teacher=teacher;
        this.student=student;
        this.selectedCourse=selectedCourse;
        this.numberofquestions = numberofquestions;
        this.marksofquestions = marksofquestions;
        this.day = day;
        this.month = month;
        this.year = year;
        this.hour = hour;
        this.minute = minute;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidebar = new javax.swing.JPanel();
        HomeSideButtonPanel = new javax.swing.JPanel();
        HomeSideButton = new javax.swing.JButton();
        StartQuizSideButtonPanel = new javax.swing.JPanel();
        StartQuizSideButton = new javax.swing.JButton();
        TeachersSideButtonPanel = new javax.swing.JPanel();
        TeachersSideButton = new javax.swing.JButton();
        StudentsSideButtonPanel = new javax.swing.JPanel();
        StudentsSideButton = new javax.swing.JButton();
        AboutUsSideButtonPanel = new javax.swing.JPanel();
        AboutUsSideButton = new javax.swing.JButton();
        SideBarQuizLabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        ExitSideButtonPanel = new javax.swing.JPanel();
        ExitSideButton = new javax.swing.JButton();
        QuizMarksheet = new javax.swing.JPanel();
        QuizStudentMarksAttendanceBottom = new javax.swing.JPanel();
        QuizStudentMarksAttendanceBottomLabel = new javax.swing.JLabel();
        QuizStudentMarksAttendanceHeader = new javax.swing.JPanel();
        QuizStudentMarksAttendanceHeaderLabel = new javax.swing.JLabel();
        QuizStudentMarksAttendanceTable = new javax.swing.JScrollPane();
        QuizMarksheetAttendanceTable = new javax.swing.JTable();
        QuizMarksheetNextButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(50, 0));

        sidebar.setBackground(new java.awt.Color(255, 255, 105));
        sidebar.setBorder(javax.swing.BorderFactory.createMatteBorder(8, 8, 8, 8, new java.awt.Color(0, 0, 0)));

        HomeSideButtonPanel.setBackground(new java.awt.Color(255, 204, 0));


        HomeSideButton.setBackground(new java.awt.Color(255, 204, 0));
        HomeSideButton.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        HomeSideButton.setText("HOME");
        HomeSideButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        HomeSideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeSideButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout HomeSideButtonPanelLayout = new javax.swing.GroupLayout(HomeSideButtonPanel);
        HomeSideButtonPanel.setLayout(HomeSideButtonPanelLayout);
        HomeSideButtonPanelLayout.setHorizontalGroup(
            HomeSideButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeSideButtonPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(HomeSideButton, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        HomeSideButtonPanelLayout.setVerticalGroup(
            HomeSideButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomeSideButtonPanelLayout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(HomeSideButton)
                .addGap(15, 15, 15))
        );

        StartQuizSideButtonPanel.setBackground(new java.awt.Color(255, 204, 0));

        StartQuizSideButton.setBackground(new java.awt.Color(255, 205, 0));
        StartQuizSideButton.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        StartQuizSideButton.setText("START QUIZ");
        StartQuizSideButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        StartQuizSideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartQuizSideButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout StartQuizSideButtonPanelLayout = new javax.swing.GroupLayout(StartQuizSideButtonPanel);
        StartQuizSideButtonPanel.setLayout(StartQuizSideButtonPanelLayout);
        StartQuizSideButtonPanelLayout.setHorizontalGroup(
            StartQuizSideButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StartQuizSideButtonPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(StartQuizSideButton, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        StartQuizSideButtonPanelLayout.setVerticalGroup(
            StartQuizSideButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StartQuizSideButtonPanelLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(StartQuizSideButton)
                .addGap(14, 14, 14))
        );

        TeachersSideButtonPanel.setBackground(new java.awt.Color(255, 204, 0));


        TeachersSideButton.setBackground(new java.awt.Color(255, 205, 0));
        TeachersSideButton.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        TeachersSideButton.setText("TEACHERS");
        TeachersSideButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        TeachersSideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeachersSideButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TeachersSideButtonPanelLayout = new javax.swing.GroupLayout(TeachersSideButtonPanel);
        TeachersSideButtonPanel.setLayout(TeachersSideButtonPanelLayout);
        TeachersSideButtonPanelLayout.setHorizontalGroup(
            TeachersSideButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TeachersSideButtonPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(TeachersSideButton, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TeachersSideButtonPanelLayout.setVerticalGroup(
            TeachersSideButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TeachersSideButtonPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(TeachersSideButton)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        StudentsSideButtonPanel.setBackground(new java.awt.Color(255, 204, 0));


        StudentsSideButton.setBackground(new java.awt.Color(255, 205, 0));
        StudentsSideButton.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        StudentsSideButton.setText("STUDENTS");
        StudentsSideButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        StudentsSideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentsSideButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout StudentsSideButtonPanelLayout = new javax.swing.GroupLayout(StudentsSideButtonPanel);
        StudentsSideButtonPanel.setLayout(StudentsSideButtonPanelLayout);
        StudentsSideButtonPanelLayout.setHorizontalGroup(
            StudentsSideButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentsSideButtonPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(StudentsSideButton, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        StudentsSideButtonPanelLayout.setVerticalGroup(
            StudentsSideButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentsSideButtonPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(StudentsSideButton)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        AboutUsSideButtonPanel.setBackground(new java.awt.Color(255, 204, 0));


        AboutUsSideButton.setBackground(new java.awt.Color(255, 205, 0));
        AboutUsSideButton.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        AboutUsSideButton.setText("ABOUT US");
        AboutUsSideButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        AboutUsSideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutUsSideButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AboutUsSideButtonPanelLayout = new javax.swing.GroupLayout(AboutUsSideButtonPanel);
        AboutUsSideButtonPanel.setLayout(AboutUsSideButtonPanelLayout);
        AboutUsSideButtonPanelLayout.setHorizontalGroup(
            AboutUsSideButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AboutUsSideButtonPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(AboutUsSideButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AboutUsSideButtonPanelLayout.setVerticalGroup(
            AboutUsSideButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AboutUsSideButtonPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(AboutUsSideButton)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        SideBarQuizLabel.setFont(new java.awt.Font("Tw Cen MT", 3, 48)); // NOI18N
        SideBarQuizLabel.setText("QUIZ");

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N

        ExitSideButtonPanel.setBackground(new java.awt.Color(255, 204, 0));

        ExitSideButton.setBackground(new java.awt.Color(255, 205, 0));
        ExitSideButton.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        ExitSideButton.setText("EXIT");
        ExitSideButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        ExitSideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitSideButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ExitSideButtonPanelLayout = new javax.swing.GroupLayout(ExitSideButtonPanel);
        ExitSideButtonPanel.setLayout(ExitSideButtonPanelLayout);
        ExitSideButtonPanelLayout.setHorizontalGroup(
            ExitSideButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ExitSideButtonPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(ExitSideButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ExitSideButtonPanelLayout.setVerticalGroup(
            ExitSideButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ExitSideButtonPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(ExitSideButton)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout sidebarLayout = new javax.swing.GroupLayout(sidebar);
        sidebar.setLayout(sidebarLayout);
        sidebarLayout.setHorizontalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HomeSideButtonPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(TeachersSideButtonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(StartQuizSideButtonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(StudentsSideButtonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidebarLayout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addGroup(sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sidebarLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(SideBarQuizLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60))
            .addComponent(AboutUsSideButtonPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ExitSideButtonPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        sidebarLayout.setVerticalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarLayout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(SideBarQuizLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138)
                .addComponent(HomeSideButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StartQuizSideButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TeachersSideButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StudentsSideButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AboutUsSideButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ExitSideButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(166, Short.MAX_VALUE))
        );

        QuizMarksheet.setBackground(new java.awt.Color(0, 0, 0));
        QuizMarksheet.setBorder(javax.swing.BorderFactory.createMatteBorder(8, 0, 8, 8, new java.awt.Color(0, 0, 0)));

        QuizStudentMarksAttendanceBottom.setBackground(new java.awt.Color(255, 255, 105));

        QuizStudentMarksAttendanceBottomLabel.setFont(new java.awt.Font("Tw Cen MT", 2, 24)); // NOI18N
        QuizStudentMarksAttendanceBottomLabel.setText("© QUIZ SYSTEM CREATED BY SHAFAY. ALL RIGHTS RESERVED!");

        javax.swing.GroupLayout QuizStudentMarksAttendanceBottomLayout = new javax.swing.GroupLayout(QuizStudentMarksAttendanceBottom);
        QuizStudentMarksAttendanceBottom.setLayout(QuizStudentMarksAttendanceBottomLayout);
        QuizStudentMarksAttendanceBottomLayout.setHorizontalGroup(
            QuizStudentMarksAttendanceBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, QuizStudentMarksAttendanceBottomLayout.createSequentialGroup()
                .addGap(383, 383, 383)
                .addComponent(QuizStudentMarksAttendanceBottomLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 930, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(309, 309, 309))
        );
        QuizStudentMarksAttendanceBottomLayout.setVerticalGroup(
            QuizStudentMarksAttendanceBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuizStudentMarksAttendanceBottomLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(QuizStudentMarksAttendanceBottomLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        QuizStudentMarksAttendanceHeader.setBackground(new java.awt.Color(255, 255, 105));

        QuizStudentMarksAttendanceHeaderLabel.setBackground(new java.awt.Color(255, 255, 105));
        QuizStudentMarksAttendanceHeaderLabel.setFont(new java.awt.Font("Tw Cen MT", 3, 36)); // NOI18N
        QuizStudentMarksAttendanceHeaderLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        QuizStudentMarksAttendanceHeaderLabel.setText("QUIZ STUDENTS MARKS/ATTENDANCE SHEET!");

        javax.swing.GroupLayout QuizStudentMarksAttendanceHeaderLayout = new javax.swing.GroupLayout(QuizStudentMarksAttendanceHeader);
        QuizStudentMarksAttendanceHeader.setLayout(QuizStudentMarksAttendanceHeaderLayout);
        QuizStudentMarksAttendanceHeaderLayout.setHorizontalGroup(
            QuizStudentMarksAttendanceHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuizStudentMarksAttendanceHeaderLayout.createSequentialGroup()
                .addGap(377, 377, 377)
                .addComponent(QuizStudentMarksAttendanceHeaderLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        QuizStudentMarksAttendanceHeaderLayout.setVerticalGroup(
            QuizStudentMarksAttendanceHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuizStudentMarksAttendanceHeaderLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(QuizStudentMarksAttendanceHeaderLabel)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        QuizMarksheetAttendanceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", "", null, "", "", null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STUDENT NAME", "COURSE", "COURSE TEACHER", "MARKS OBTAINED", "TOTAL MARKS", "PERCENTAGE", "GRADE", "ATTENDANCE"
            }
        ));
        QuizStudentMarksAttendanceTable.setViewportView(QuizMarksheetAttendanceTable);

        QuizMarksheetNextButton.setBackground(new java.awt.Color(255, 204, 0));
        QuizMarksheetNextButton.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        QuizMarksheetNextButton.setText("NEXT!");
        QuizMarksheetNextButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        QuizMarksheetNextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuizMarksheetNextButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout QuizMarksheetLayout = new javax.swing.GroupLayout(QuizMarksheet);
        QuizMarksheet.setLayout(QuizMarksheetLayout);
        QuizMarksheetLayout.setHorizontalGroup(
            QuizMarksheetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(QuizStudentMarksAttendanceBottom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(QuizStudentMarksAttendanceHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, QuizMarksheetLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(QuizMarksheetNextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(825, 825, 825))
            .addGroup(QuizMarksheetLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(QuizStudentMarksAttendanceTable, javax.swing.GroupLayout.PREFERRED_SIZE, 1222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        QuizMarksheetLayout.setVerticalGroup(
            QuizMarksheetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, QuizMarksheetLayout.createSequentialGroup()
                .addComponent(QuizStudentMarksAttendanceHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(QuizStudentMarksAttendanceTable, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addComponent(QuizMarksheetNextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(QuizStudentMarksAttendanceBottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sidebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(QuizMarksheet, javax.swing.GroupLayout.PREFERRED_SIZE, 1393, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, 0)
                        .addComponent(QuizMarksheet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(sidebar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomeSideButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeSideButtonActionPerformed
        // TODO add your handling code here:
        new homepage().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_HomeSideButtonActionPerformed



    private void StartQuizSideButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartQuizSideButtonActionPerformed

        // TODO add your handling code here:
        new QuizRegistration().setVisible(true);
        setVisible(false);

    }//GEN-LAST:event_StartQuizSideButtonActionPerformed



    private void TeachersSideButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeachersSideButtonActionPerformed
        // TODO add your handling code here
        new TeachersData().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_TeachersSideButtonActionPerformed



    private void StudentsSideButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentsSideButtonActionPerformed
        new StudentsData().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_StudentsSideButtonActionPerformed



    private void AboutUsSideButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutUsSideButtonActionPerformed
        // TODO add your handling

        new AboutUs().setVisible(true);
        setVisible(false);

    }//GEN-LAST:event_AboutUsSideButtonActionPerformed



    private void ExitSideButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitSideButtonActionPerformed
        // TODO add your handling code here:

        setVisible(false);
    }//GEN-LAST:event_ExitSideButtonActionPerformed


    private void QuizMarksheetNextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuizMarksheetNextButtonActionPerformed
        // TODO add your handling code here:
        new QuizEnded().setVisible(true);
        setVisible(false);
    
    }//GEN-LAST:event_QuizMarksheetNextButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuizMarksheet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuizMarksheet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuizMarksheet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuizMarksheet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AboutUsSideButton;
    private javax.swing.JPanel AboutUsSideButtonPanel;
    private javax.swing.JButton ExitSideButton;
    private javax.swing.JPanel ExitSideButtonPanel;
    private javax.swing.JButton HomeSideButton;
    private javax.swing.JPanel HomeSideButtonPanel;
    private javax.swing.JPanel QuizMarksheet;
    private javax.swing.JTable QuizMarksheetAttendanceTable;
    private javax.swing.JButton QuizMarksheetNextButton;
    private javax.swing.JPanel QuizStudentMarksAttendanceBottom;
    private javax.swing.JLabel QuizStudentMarksAttendanceBottomLabel;
    private javax.swing.JPanel QuizStudentMarksAttendanceHeader;
    private javax.swing.JLabel QuizStudentMarksAttendanceHeaderLabel;
    private javax.swing.JScrollPane QuizStudentMarksAttendanceTable;
    private javax.swing.JLabel SideBarQuizLabel;
    private javax.swing.JButton StartQuizSideButton;
    private javax.swing.JPanel StartQuizSideButtonPanel;
    private javax.swing.JButton StudentsSideButton;
    private javax.swing.JPanel StudentsSideButtonPanel;
    private javax.swing.JButton TeachersSideButton;
    private javax.swing.JPanel TeachersSideButtonPanel;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel sidebar;
    // End of variables declaration//GEN-END:variables
}
