
package com.mycompany.projectguitrying;

/**
 *
 * @author SHAFAY
 */
public class QuizAnswerKey extends javax.swing.JFrame {

    /**
     * Creates new form QuizAnswerKey
     */
    String q1StudentAnswer;
    String q2StudentAnswer;
    String q3StudentAnswer;
    String q4StudentAnswer;
    String q5StudentAnswer;
    String q6StudentAnswer;
    String q7StudentAnswer;
    String numberofquestions;
    int marksofquestions;
    String day;
    String month;
    String year;
    String hour;
    String minute;
    String mcq1;
    String mcq1optA;
    String mcq1optB;
    String mcq1optC;
    String mcq1optD;
    String mcq1Correctopt;
    String mcq2;
    String mcq2optA;
    String mcq2optB;
    String mcq2optC;
    String mcq2optD;
    String mcq2Correctopt;
    String mcq3;
    String mcq3optA;
    String mcq3optB;
    String mcq3optC;
    String mcq3optD;
    String mcq3Correctopt;
    String mcq4;
    String mcq4optA;
    String mcq4optB;
    String mcq4optC;
    String mcq4optD;
    String mcq4Correctopt;
    String tf1;
    String tf1Correctopt;
    String tf2;
    String tf2Correctopt;
    String tf3;
    String tf3Correctopt;
    String teacher;
    String student;
    String selectedCourse;
    String CourseTopic1;

    public QuizAnswerKey(String q1StudentAnswer, String q2StudentAnswer, String q3StudentAnswer, String q4StudentAnswer, String q5StudentAnswer, String q6StudentAnswer, String q7StudentAnswer,String CourseTopic1, String numberofquestions, int marksofquestions, String day, String month, String year, String hour, String minute, String mcq1, String mcq1optA, String mcq1optB, String mcq1optC, String mcq1optD, String mcq1Correctopt, String mcq2, String mcq2optA, String mcq2optB, String mcq2optC, String mcq2optD, String mcq2Correctopt, String mcq3, String mcq3optA, String mcq3optB, String mcq3optC, String mcq3optD, String mcq3Correctopt, String mcq4, String mcq4optA, String mcq4optB, String mcq4optC, String mcq4optD, String mcq4Correctopt, String tf1, String tf1Correctopt, String tf2, String tf2Correctopt, String tf3, String tf3Correctopt, String teacher, String student, String selectedCourse) {

        this.CourseTopic1=CourseTopic1;
        this.q1StudentAnswer=q1StudentAnswer;
        this.q2StudentAnswer=q2StudentAnswer;
        this.q3StudentAnswer=q3StudentAnswer;
        this.q4StudentAnswer=q4StudentAnswer;
        this.q5StudentAnswer=q5StudentAnswer;
        this.q6StudentAnswer=q6StudentAnswer;
        this.q7StudentAnswer=q7StudentAnswer;
        this.mcq1=mcq1;
        this.mcq1optA=mcq1optA;
        this.mcq1optB=mcq1optB;
        this.mcq1optC=mcq1optC;
        this.mcq1optD=mcq1optD;
        this.mcq1Correctopt=mcq1Correctopt;
        this.mcq2=mcq2;
        this.mcq2optA=mcq2optA;
        this.mcq2optB=mcq2optB;
        this.mcq2optC=mcq2optC;
        this.mcq2optD=mcq2optD;
        this.mcq2Correctopt=mcq2Correctopt;
        this.mcq3=mcq3;
        this.mcq3optA=mcq3optA;
        this.mcq3optB=mcq3optB;
        this.mcq3optC=mcq3optC;
        this.mcq3optD=mcq3optD;
        this.mcq3Correctopt=mcq3Correctopt;
        this.mcq4=mcq4;
        this.mcq4optA=mcq4optA;
        this.mcq4optB=mcq4optB;
        this.mcq4optC=mcq4optC;
        this.mcq4optD=mcq4optD;
        this.mcq4Correctopt=mcq4Correctopt;
        this.tf1=tf1;
        this.tf1Correctopt=tf1Correctopt;
        this.tf2=tf2;
        this.tf2Correctopt=tf2Correctopt;
        this.tf3=tf3;
        this.tf3Correctopt=tf3Correctopt;
        this.teacher=teacher;
        this.student=student;
        this.selectedCourse=selectedCourse;
        this.numberofquestions = numberofquestions;
        this.marksofquestions = marksofquestions;
        this.day = day;
        this.month = month;
        this.year = year;
        this.hour = hour;
        this.minute = minute;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidebar = new javax.swing.JPanel();
        HomeSideButtonPanel = new javax.swing.JPanel();
        HomeSideButton = new javax.swing.JButton();
        StartQuizSideButtonPanel = new javax.swing.JPanel();
        StartQuizSideButton = new javax.swing.JButton();
        TeachersSideButtonPanel = new javax.swing.JPanel();
        TeachersSideButton = new javax.swing.JButton();
        StudentsSideButtonPanel = new javax.swing.JPanel();
        StudentsSideButton = new javax.swing.JButton();
        AboutUsSideButtonPanel = new javax.swing.JPanel();
        AboutUsSideButton = new javax.swing.JButton();
        SideBarQuizLabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        ExitSideButtonPanel = new javax.swing.JPanel();
        ExitSideButton = new javax.swing.JButton();
        QuizAnswerKey = new javax.swing.JPanel();
        QuizAnswerKeyHeader = new javax.swing.JPanel();
        QuizAnswerKeyHeaderLabel = new javax.swing.JLabel();
        QuizAnswerKeySubmittedLabel = new javax.swing.JLabel();
        jSeparator17 = new javax.swing.JSeparator();
        QuizAnswerKeyQ1Panel = new javax.swing.JPanel();
        QuizAnswerKeyQ1Mcq1Label = new javax.swing.JLabel();
        QuizAnswerKeyQ1CorrectAnswerLabel = new javax.swing.JLabel();
        QuizAnswerKeyQ1YourAnswerLabel = new javax.swing.JLabel();
        QuizAnswerKeyQ2Panel = new javax.swing.JPanel();
        QuizAnswerKeyQ2Mcq3Label = new javax.swing.JLabel();
        QuizAnswerKeyQ2CorrectAnswerLabel = new javax.swing.JLabel();
        QuizAnswerKeyQ2YourAnswerLabel = new javax.swing.JLabel();
        QuizAnswerKeyQ3Panel = new javax.swing.JPanel();
        QuizAnswerKeyQ3Tf1Label = new javax.swing.JLabel();
        QuizAnswerKeyQ3YourAnswerLabel = new javax.swing.JLabel();
        QuizAnswerKeyQ3CorrectAnswerLabel = new javax.swing.JLabel();
        QuizAnswerKeyQ4Panel = new javax.swing.JPanel();
        QuizAnswerKeyQ4Tf3Label = new javax.swing.JLabel();
        QuizAnswerKeyQ4CorrectAnswerLabel = new javax.swing.JLabel();
        QuizAnswerKeyQ4YourAnswerLabel = new javax.swing.JLabel();
        QuizAnswerKeyQ5Panel = new javax.swing.JPanel();
        QuizAnswerKeyQ5Mcq2Label = new javax.swing.JLabel();
        QuizAnswerKeyQ5CorrectAnswerLabel = new javax.swing.JLabel();
        QuizAnswerKeyQ5YourAnswerLabel = new javax.swing.JLabel();
        QuizAnswerKeyQ6Panel = new javax.swing.JPanel();
        QuizAnswerKeyQ6Tf2Label = new javax.swing.JLabel();
        QuizAnswerKeyQ6CorrectAnswerLabel = new javax.swing.JLabel();
        QuizAnswerKeyQ6YourAnswerLabel = new javax.swing.JLabel();
        QuizAnswerKeyQ7Panel = new javax.swing.JPanel();
        QuizAnswerKeyQ7Mcq4Label = new javax.swing.JLabel();
        QuizAnswerKeyQ7YourAnswerLabel = new javax.swing.JLabel();
        QuizAnswerKeyQ7CorrectAnswerLabel = new javax.swing.JLabel();
        AnswerKeyNextButton = new javax.swing.JButton();
        QuizAnswerKeyBottom = new javax.swing.JPanel();
        QuizAnswerKeyBottomLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1791, 1023));
        setLocation(new java.awt.Point(50, 0));

        sidebar.setBackground(new java.awt.Color(255, 255, 105));
        sidebar.setBorder(javax.swing.BorderFactory.createMatteBorder(8, 8, 8, 8, new java.awt.Color(0, 0, 0)));

        HomeSideButtonPanel.setBackground(new java.awt.Color(255, 204, 0));


        HomeSideButton.setBackground(new java.awt.Color(255, 204, 0));
        HomeSideButton.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        HomeSideButton.setText("HOME");
        HomeSideButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        HomeSideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeSideButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout HomeSideButtonPanelLayout = new javax.swing.GroupLayout(HomeSideButtonPanel);
        HomeSideButtonPanel.setLayout(HomeSideButtonPanelLayout);
        HomeSideButtonPanelLayout.setHorizontalGroup(
            HomeSideButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeSideButtonPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(HomeSideButton, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        HomeSideButtonPanelLayout.setVerticalGroup(
            HomeSideButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomeSideButtonPanelLayout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(HomeSideButton)
                .addGap(15, 15, 15))
        );

        StartQuizSideButtonPanel.setBackground(new java.awt.Color(255, 204, 0));


        StartQuizSideButton.setBackground(new java.awt.Color(255, 205, 0));
        StartQuizSideButton.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        StartQuizSideButton.setText("START QUIZ");
        StartQuizSideButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        StartQuizSideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartQuizSideButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout StartQuizSideButtonPanelLayout = new javax.swing.GroupLayout(StartQuizSideButtonPanel);
        StartQuizSideButtonPanel.setLayout(StartQuizSideButtonPanelLayout);
        StartQuizSideButtonPanelLayout.setHorizontalGroup(
            StartQuizSideButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StartQuizSideButtonPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(StartQuizSideButton, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        StartQuizSideButtonPanelLayout.setVerticalGroup(
            StartQuizSideButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StartQuizSideButtonPanelLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(StartQuizSideButton)
                .addGap(14, 14, 14))
        );

        TeachersSideButtonPanel.setBackground(new java.awt.Color(255, 204, 0));


        TeachersSideButton.setBackground(new java.awt.Color(255, 205, 0));
        TeachersSideButton.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        TeachersSideButton.setText("TEACHERS");
        TeachersSideButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        TeachersSideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeachersSideButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TeachersSideButtonPanelLayout = new javax.swing.GroupLayout(TeachersSideButtonPanel);
        TeachersSideButtonPanel.setLayout(TeachersSideButtonPanelLayout);
        TeachersSideButtonPanelLayout.setHorizontalGroup(
            TeachersSideButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TeachersSideButtonPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(TeachersSideButton, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TeachersSideButtonPanelLayout.setVerticalGroup(
            TeachersSideButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TeachersSideButtonPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(TeachersSideButton)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        StudentsSideButtonPanel.setBackground(new java.awt.Color(255, 204, 0));


        StudentsSideButton.setBackground(new java.awt.Color(255, 205, 0));
        StudentsSideButton.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        StudentsSideButton.setText("STUDENTS");
        StudentsSideButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        StudentsSideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentsSideButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout StudentsSideButtonPanelLayout = new javax.swing.GroupLayout(StudentsSideButtonPanel);
        StudentsSideButtonPanel.setLayout(StudentsSideButtonPanelLayout);
        StudentsSideButtonPanelLayout.setHorizontalGroup(
            StudentsSideButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentsSideButtonPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(StudentsSideButton, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        StudentsSideButtonPanelLayout.setVerticalGroup(
            StudentsSideButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentsSideButtonPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(StudentsSideButton)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        AboutUsSideButtonPanel.setBackground(new java.awt.Color(255, 204, 0));


        AboutUsSideButton.setBackground(new java.awt.Color(255, 205, 0));
        AboutUsSideButton.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        AboutUsSideButton.setText("ABOUT US");
        AboutUsSideButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        AboutUsSideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutUsSideButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AboutUsSideButtonPanelLayout = new javax.swing.GroupLayout(AboutUsSideButtonPanel);
        AboutUsSideButtonPanel.setLayout(AboutUsSideButtonPanelLayout);
        AboutUsSideButtonPanelLayout.setHorizontalGroup(
            AboutUsSideButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AboutUsSideButtonPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(AboutUsSideButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AboutUsSideButtonPanelLayout.setVerticalGroup(
            AboutUsSideButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AboutUsSideButtonPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(AboutUsSideButton)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        SideBarQuizLabel.setFont(new java.awt.Font("Tw Cen MT", 3, 48)); // NOI18N
        SideBarQuizLabel.setText("QUIZ");

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N

        ExitSideButtonPanel.setBackground(new java.awt.Color(255, 204, 0));
        ExitSideButtonPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitSideButtonPanelMouseClicked(evt);
            }
        });

        ExitSideButton.setBackground(new java.awt.Color(255, 205, 0));
        ExitSideButton.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        ExitSideButton.setText("EXIT");
        ExitSideButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        ExitSideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitSideButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ExitSideButtonPanelLayout = new javax.swing.GroupLayout(ExitSideButtonPanel);
        ExitSideButtonPanel.setLayout(ExitSideButtonPanelLayout);
        ExitSideButtonPanelLayout.setHorizontalGroup(
            ExitSideButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ExitSideButtonPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(ExitSideButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ExitSideButtonPanelLayout.setVerticalGroup(
            ExitSideButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ExitSideButtonPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(ExitSideButton)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout sidebarLayout = new javax.swing.GroupLayout(sidebar);
        sidebar.setLayout(sidebarLayout);
        sidebarLayout.setHorizontalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HomeSideButtonPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(TeachersSideButtonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(StartQuizSideButtonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(StudentsSideButtonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidebarLayout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addGroup(sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sidebarLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(SideBarQuizLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60))
            .addComponent(AboutUsSideButtonPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ExitSideButtonPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        sidebarLayout.setVerticalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarLayout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(SideBarQuizLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138)
                .addComponent(HomeSideButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StartQuizSideButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TeachersSideButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StudentsSideButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AboutUsSideButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ExitSideButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(160, Short.MAX_VALUE))
        );

        QuizAnswerKey.setBackground(new java.awt.Color(0, 0, 0));
        QuizAnswerKey.setBorder(javax.swing.BorderFactory.createMatteBorder(8, 0, 8, 8, new java.awt.Color(0, 0, 0)));

        QuizAnswerKeyHeader.setBackground(new java.awt.Color(255, 255, 105));

        QuizAnswerKeyHeaderLabel.setBackground(new java.awt.Color(255, 255, 105));
        QuizAnswerKeyHeaderLabel.setFont(new java.awt.Font("Tw Cen MT", 3, 36)); // NOI18N
        QuizAnswerKeyHeaderLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        QuizAnswerKeyHeaderLabel.setText("QUIZ ANSWER KEY!");

        javax.swing.GroupLayout QuizAnswerKeyHeaderLayout = new javax.swing.GroupLayout(QuizAnswerKeyHeader);
        QuizAnswerKeyHeader.setLayout(QuizAnswerKeyHeaderLayout);
        QuizAnswerKeyHeaderLayout.setHorizontalGroup(
            QuizAnswerKeyHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, QuizAnswerKeyHeaderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(QuizAnswerKeyHeaderLabel)
                .addGap(536, 536, 536))
        );
        QuizAnswerKeyHeaderLayout.setVerticalGroup(
            QuizAnswerKeyHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, QuizAnswerKeyHeaderLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(QuizAnswerKeyHeaderLabel)
                .addGap(22, 22, 22))
        );

        QuizAnswerKeySubmittedLabel.setBackground(new java.awt.Color(0, 0, 0));
        QuizAnswerKeySubmittedLabel.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        QuizAnswerKeySubmittedLabel.setForeground(new java.awt.Color(255, 255, 255));
        QuizAnswerKeySubmittedLabel.setText("QUIZ SUBMITTED SUCCESSFULLY! THE ANSWER KEY WILL DISPLAY NOW!");

        jSeparator17.setForeground(new java.awt.Color(255, 255, 255));

        QuizAnswerKeyQ1Panel.setBackground(new java.awt.Color(0, 0, 0));
        QuizAnswerKeyQ1Panel.setVisible(false);

        QuizAnswerKeyQ1Mcq1Label.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        QuizAnswerKeyQ1Mcq1Label.setForeground(new java.awt.Color(255, 255, 255));
        QuizAnswerKeyQ1Mcq1Label.setText("Q1) "+mcq1);

        QuizAnswerKeyQ1CorrectAnswerLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        QuizAnswerKeyQ1CorrectAnswerLabel.setForeground(new java.awt.Color(255, 255, 255));
        QuizAnswerKeyQ1CorrectAnswerLabel.setText("CORRECT ANSWER: "+mcq1Correctopt);

        QuizAnswerKeyQ1YourAnswerLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        QuizAnswerKeyQ1YourAnswerLabel.setForeground(new java.awt.Color(255, 255, 255));
        QuizAnswerKeyQ1YourAnswerLabel.setText("YOUR ANSWER: "+q1StudentAnswer);

        javax.swing.GroupLayout QuizAnswerKeyQ1PanelLayout = new javax.swing.GroupLayout(QuizAnswerKeyQ1Panel);
        QuizAnswerKeyQ1Panel.setLayout(QuizAnswerKeyQ1PanelLayout);
        QuizAnswerKeyQ1PanelLayout.setHorizontalGroup(
            QuizAnswerKeyQ1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuizAnswerKeyQ1PanelLayout.createSequentialGroup()
                .addGroup(QuizAnswerKeyQ1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(QuizAnswerKeyQ1PanelLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(QuizAnswerKeyQ1CorrectAnswerLabel)
                        .addGap(220, 220, 220)
                        .addComponent(QuizAnswerKeyQ1YourAnswerLabel))
                    .addGroup(QuizAnswerKeyQ1PanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(QuizAnswerKeyQ1Mcq1Label)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        QuizAnswerKeyQ1PanelLayout.setVerticalGroup(
            QuizAnswerKeyQ1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuizAnswerKeyQ1PanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(QuizAnswerKeyQ1Mcq1Label)
                .addGap(18, 18, 18)
                .addGroup(QuizAnswerKeyQ1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(QuizAnswerKeyQ1CorrectAnswerLabel)
                    .addComponent(QuizAnswerKeyQ1YourAnswerLabel)))
        );

        QuizAnswerKeyQ2Panel.setBackground(new java.awt.Color(0, 0, 0));
        QuizAnswerKeyQ2Panel.setVisible(false);

        QuizAnswerKeyQ2Mcq3Label.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        QuizAnswerKeyQ2Mcq3Label.setForeground(new java.awt.Color(255, 255, 255));
        QuizAnswerKeyQ2Mcq3Label.setText("Q2) "+mcq3);

        QuizAnswerKeyQ2CorrectAnswerLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        QuizAnswerKeyQ2CorrectAnswerLabel.setForeground(new java.awt.Color(255, 255, 255));
        QuizAnswerKeyQ2CorrectAnswerLabel.setText("CORRECT ANSWER: "+mcq3Correctopt);

        QuizAnswerKeyQ2YourAnswerLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        QuizAnswerKeyQ2YourAnswerLabel.setForeground(new java.awt.Color(255, 255, 255));
        QuizAnswerKeyQ2YourAnswerLabel.setText("YOUR ANSWER: "+q2StudentAnswer);

        javax.swing.GroupLayout QuizAnswerKeyQ2PanelLayout = new javax.swing.GroupLayout(QuizAnswerKeyQ2Panel);
        QuizAnswerKeyQ2Panel.setLayout(QuizAnswerKeyQ2PanelLayout);
        QuizAnswerKeyQ2PanelLayout.setHorizontalGroup(
            QuizAnswerKeyQ2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuizAnswerKeyQ2PanelLayout.createSequentialGroup()
                .addGroup(QuizAnswerKeyQ2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(QuizAnswerKeyQ2PanelLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(QuizAnswerKeyQ2CorrectAnswerLabel)
                        .addGap(224, 224, 224)
                        .addComponent(QuizAnswerKeyQ2YourAnswerLabel))
                    .addGroup(QuizAnswerKeyQ2PanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(QuizAnswerKeyQ2Mcq3Label)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        QuizAnswerKeyQ2PanelLayout.setVerticalGroup(
            QuizAnswerKeyQ2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuizAnswerKeyQ2PanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(QuizAnswerKeyQ2Mcq3Label)
                .addGap(18, 18, 18)
                .addGroup(QuizAnswerKeyQ2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(QuizAnswerKeyQ2CorrectAnswerLabel)
                    .addComponent(QuizAnswerKeyQ2YourAnswerLabel)))
        );

        QuizAnswerKeyQ3Panel.setBackground(new java.awt.Color(0, 0, 0));
        QuizAnswerKeyQ3Panel.setVisible(false);

        QuizAnswerKeyQ3Tf1Label.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        QuizAnswerKeyQ3Tf1Label.setForeground(new java.awt.Color(255, 255, 255));
        QuizAnswerKeyQ3Tf1Label.setText("Q3) "+tf1);

        QuizAnswerKeyQ3YourAnswerLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        QuizAnswerKeyQ3YourAnswerLabel.setForeground(new java.awt.Color(255, 255, 255));
        QuizAnswerKeyQ3YourAnswerLabel.setText("YOUR ANSWER: "+q3StudentAnswer);

        QuizAnswerKeyQ3CorrectAnswerLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        QuizAnswerKeyQ3CorrectAnswerLabel.setForeground(new java.awt.Color(255, 255, 255));
        QuizAnswerKeyQ3CorrectAnswerLabel.setText("CORRECT ANSWER: "+tf1Correctopt);

        javax.swing.GroupLayout QuizAnswerKeyQ3PanelLayout = new javax.swing.GroupLayout(QuizAnswerKeyQ3Panel);
        QuizAnswerKeyQ3Panel.setLayout(QuizAnswerKeyQ3PanelLayout);
        QuizAnswerKeyQ3PanelLayout.setHorizontalGroup(
            QuizAnswerKeyQ3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuizAnswerKeyQ3PanelLayout.createSequentialGroup()
                .addGroup(QuizAnswerKeyQ3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(QuizAnswerKeyQ3PanelLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(QuizAnswerKeyQ3CorrectAnswerLabel)
                        .addGap(226, 226, 226)
                        .addComponent(QuizAnswerKeyQ3YourAnswerLabel))
                    .addGroup(QuizAnswerKeyQ3PanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(QuizAnswerKeyQ3Tf1Label)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        QuizAnswerKeyQ3PanelLayout.setVerticalGroup(
            QuizAnswerKeyQ3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuizAnswerKeyQ3PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(QuizAnswerKeyQ3Tf1Label)
                .addGap(18, 18, 18)
                .addGroup(QuizAnswerKeyQ3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(QuizAnswerKeyQ3CorrectAnswerLabel)
                    .addComponent(QuizAnswerKeyQ3YourAnswerLabel))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        QuizAnswerKeyQ4Panel.setBackground(new java.awt.Color(0, 0, 0));
        QuizAnswerKeyQ4Panel.setVisible(false);

        QuizAnswerKeyQ4Tf3Label.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        QuizAnswerKeyQ4Tf3Label.setForeground(new java.awt.Color(255, 255, 255));
        QuizAnswerKeyQ4Tf3Label.setText("Q4) "+tf3);

        QuizAnswerKeyQ4CorrectAnswerLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        QuizAnswerKeyQ4CorrectAnswerLabel.setForeground(new java.awt.Color(255, 255, 255));
        QuizAnswerKeyQ4CorrectAnswerLabel.setText("CORRECT ANSWER: "+tf3Correctopt);

        QuizAnswerKeyQ4YourAnswerLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        QuizAnswerKeyQ4YourAnswerLabel.setForeground(new java.awt.Color(255, 255, 255));
        QuizAnswerKeyQ4YourAnswerLabel.setText("YOUR ANSWER: "+q4StudentAnswer);

        javax.swing.GroupLayout QuizAnswerKeyQ4PanelLayout = new javax.swing.GroupLayout(QuizAnswerKeyQ4Panel);
        QuizAnswerKeyQ4Panel.setLayout(QuizAnswerKeyQ4PanelLayout);
        QuizAnswerKeyQ4PanelLayout.setHorizontalGroup(
            QuizAnswerKeyQ4PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuizAnswerKeyQ4PanelLayout.createSequentialGroup()
                .addGroup(QuizAnswerKeyQ4PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(QuizAnswerKeyQ4PanelLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(QuizAnswerKeyQ4CorrectAnswerLabel)
                        .addGap(233, 233, 233)
                        .addComponent(QuizAnswerKeyQ4YourAnswerLabel))
                    .addGroup(QuizAnswerKeyQ4PanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(QuizAnswerKeyQ4Tf3Label)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        QuizAnswerKeyQ4PanelLayout.setVerticalGroup(
            QuizAnswerKeyQ4PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuizAnswerKeyQ4PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(QuizAnswerKeyQ4Tf3Label)
                .addGap(18, 18, 18)
                .addGroup(QuizAnswerKeyQ4PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(QuizAnswerKeyQ4CorrectAnswerLabel)
                    .addComponent(QuizAnswerKeyQ4YourAnswerLabel))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        QuizAnswerKeyQ5Panel.setBackground(new java.awt.Color(0, 0, 0));
        QuizAnswerKeyQ5Panel.setVisible(false);

        QuizAnswerKeyQ5Mcq2Label.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        QuizAnswerKeyQ5Mcq2Label.setForeground(new java.awt.Color(255, 255, 255));
        QuizAnswerKeyQ5Mcq2Label.setText("Q5) "+mcq2);

        QuizAnswerKeyQ5CorrectAnswerLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        QuizAnswerKeyQ5CorrectAnswerLabel.setForeground(new java.awt.Color(255, 255, 255));
        QuizAnswerKeyQ5CorrectAnswerLabel.setText("CORRECT ANSWER: "+mcq2Correctopt);

        QuizAnswerKeyQ5YourAnswerLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        QuizAnswerKeyQ5YourAnswerLabel.setForeground(new java.awt.Color(255, 255, 255));
        QuizAnswerKeyQ5YourAnswerLabel.setText("YOUR ANSWER: "+q5StudentAnswer);

        QuizAnswerKeyQ6Panel.setBackground(new java.awt.Color(0, 0, 0));
        QuizAnswerKeyQ6Panel.setVisible(false);

        QuizAnswerKeyQ6Tf2Label.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        QuizAnswerKeyQ6Tf2Label.setForeground(new java.awt.Color(255, 255, 255));
        QuizAnswerKeyQ6Tf2Label.setText("Q6) "+tf2);

        QuizAnswerKeyQ6CorrectAnswerLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        QuizAnswerKeyQ6CorrectAnswerLabel.setForeground(new java.awt.Color(255, 255, 255));
        QuizAnswerKeyQ6CorrectAnswerLabel.setText("CORRECT ANSWER: "+tf2Correctopt);

        QuizAnswerKeyQ6YourAnswerLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        QuizAnswerKeyQ6YourAnswerLabel.setForeground(new java.awt.Color(255, 255, 255));
        QuizAnswerKeyQ6YourAnswerLabel.setText("YOUR ANSWER: "+q6StudentAnswer);

        javax.swing.GroupLayout QuizAnswerKeyQ6PanelLayout = new javax.swing.GroupLayout(QuizAnswerKeyQ6Panel);
        QuizAnswerKeyQ6Panel.setLayout(QuizAnswerKeyQ6PanelLayout);
        QuizAnswerKeyQ6PanelLayout.setHorizontalGroup(
            QuizAnswerKeyQ6PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuizAnswerKeyQ6PanelLayout.createSequentialGroup()
                .addGroup(QuizAnswerKeyQ6PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(QuizAnswerKeyQ6PanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(QuizAnswerKeyQ6Tf2Label))
                    .addGroup(QuizAnswerKeyQ6PanelLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(QuizAnswerKeyQ6CorrectAnswerLabel)
                        .addGap(232, 232, 232)
                        .addComponent(QuizAnswerKeyQ6YourAnswerLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        QuizAnswerKeyQ6PanelLayout.setVerticalGroup(
            QuizAnswerKeyQ6PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuizAnswerKeyQ6PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(QuizAnswerKeyQ6Tf2Label)
                .addGap(18, 18, 18)
                .addGroup(QuizAnswerKeyQ6PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(QuizAnswerKeyQ6CorrectAnswerLabel)
                    .addComponent(QuizAnswerKeyQ6YourAnswerLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        QuizAnswerKeyQ7Panel.setBackground(new java.awt.Color(0, 0, 0));
        QuizAnswerKeyQ7Panel.setVisible(false);

        QuizAnswerKeyQ7Mcq4Label.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        QuizAnswerKeyQ7Mcq4Label.setForeground(new java.awt.Color(255, 255, 255));
        QuizAnswerKeyQ7Mcq4Label.setText("Q7) "+mcq4);

        QuizAnswerKeyQ7YourAnswerLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        QuizAnswerKeyQ7YourAnswerLabel.setForeground(new java.awt.Color(255, 255, 255));
        QuizAnswerKeyQ7YourAnswerLabel.setText("YOUR ANSWER: "+q7StudentAnswer);

        QuizAnswerKeyQ7CorrectAnswerLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        QuizAnswerKeyQ7CorrectAnswerLabel.setForeground(new java.awt.Color(255, 255, 255));
        QuizAnswerKeyQ7CorrectAnswerLabel.setText("CORRECT ANSWER: "+mcq4Correctopt);

        javax.swing.GroupLayout QuizAnswerKeyQ7PanelLayout = new javax.swing.GroupLayout(QuizAnswerKeyQ7Panel);
        QuizAnswerKeyQ7Panel.setLayout(QuizAnswerKeyQ7PanelLayout);
        QuizAnswerKeyQ7PanelLayout.setHorizontalGroup(
            QuizAnswerKeyQ7PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuizAnswerKeyQ7PanelLayout.createSequentialGroup()
                .addGroup(QuizAnswerKeyQ7PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(QuizAnswerKeyQ7PanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(QuizAnswerKeyQ7Mcq4Label))
                    .addGroup(QuizAnswerKeyQ7PanelLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(QuizAnswerKeyQ7CorrectAnswerLabel)
                        .addGap(232, 232, 232)
                        .addComponent(QuizAnswerKeyQ7YourAnswerLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        QuizAnswerKeyQ7PanelLayout.setVerticalGroup(
            QuizAnswerKeyQ7PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuizAnswerKeyQ7PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(QuizAnswerKeyQ7Mcq4Label)
                .addGap(18, 18, 18)
                .addGroup(QuizAnswerKeyQ7PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(QuizAnswerKeyQ7CorrectAnswerLabel)
                    .addComponent(QuizAnswerKeyQ7YourAnswerLabel))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout QuizAnswerKeyQ5PanelLayout = new javax.swing.GroupLayout(QuizAnswerKeyQ5Panel);
        QuizAnswerKeyQ5Panel.setLayout(QuizAnswerKeyQ5PanelLayout);
        QuizAnswerKeyQ5PanelLayout.setHorizontalGroup(
            QuizAnswerKeyQ5PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuizAnswerKeyQ5PanelLayout.createSequentialGroup()
                .addGroup(QuizAnswerKeyQ5PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(QuizAnswerKeyQ5PanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(QuizAnswerKeyQ5Mcq2Label))
                    .addGroup(QuizAnswerKeyQ5PanelLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(QuizAnswerKeyQ5CorrectAnswerLabel)
                        .addGap(231, 231, 231)
                        .addComponent(QuizAnswerKeyQ5YourAnswerLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(QuizAnswerKeyQ6Panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(QuizAnswerKeyQ7Panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        QuizAnswerKeyQ5PanelLayout.setVerticalGroup(
            QuizAnswerKeyQ5PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuizAnswerKeyQ5PanelLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(QuizAnswerKeyQ5Mcq2Label)
                .addGap(18, 18, 18)
                .addGroup(QuizAnswerKeyQ5PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(QuizAnswerKeyQ5CorrectAnswerLabel)
                    .addComponent(QuizAnswerKeyQ5YourAnswerLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(QuizAnswerKeyQ6Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(QuizAnswerKeyQ7Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        if (numberofquestions=="3"){
            QuizAnswerKeyQ1Panel.setVisible(true);
            QuizAnswerKeyQ2Panel.setVisible(true);
            QuizAnswerKeyQ3Panel.setVisible(true);
        }
        else if (numberofquestions=="4") {
            QuizAnswerKeyQ1Panel.setVisible(true);
            QuizAnswerKeyQ2Panel.setVisible(true);
            QuizAnswerKeyQ3Panel.setVisible(true);
            QuizAnswerKeyQ4Panel.setVisible(true);
        }
        else if (numberofquestions=="5") {
            QuizAnswerKeyQ1Panel.setVisible(true);
            QuizAnswerKeyQ2Panel.setVisible(true);
            QuizAnswerKeyQ3Panel.setVisible(true);
            QuizAnswerKeyQ4Panel.setVisible(true);
            QuizAnswerKeyQ5Panel.setVisible(true);
        }
        else if (numberofquestions=="6") {
            QuizAnswerKeyQ1Panel.setVisible(true);
            QuizAnswerKeyQ2Panel.setVisible(true);
            QuizAnswerKeyQ3Panel.setVisible(true);
            QuizAnswerKeyQ4Panel.setVisible(true);
            QuizAnswerKeyQ5Panel.setVisible(true);
            QuizAnswerKeyQ6Panel.setVisible(true);
        }
        else {
            QuizAnswerKeyQ1Panel.setVisible(true);
            QuizAnswerKeyQ2Panel.setVisible(true);
            QuizAnswerKeyQ3Panel.setVisible(true);
            QuizAnswerKeyQ4Panel.setVisible(true);
            QuizAnswerKeyQ5Panel.setVisible(true);
            QuizAnswerKeyQ6Panel.setVisible(true);
            QuizAnswerKeyQ7Panel.setVisible(true);
        }

        AnswerKeyNextButton.setBackground(new java.awt.Color(255, 204, 0));
        AnswerKeyNextButton.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        AnswerKeyNextButton.setText("NEXT!");
        AnswerKeyNextButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        AnswerKeyNextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnswerKeyNextButtonActionPerformed(evt);
            }
        });

        QuizAnswerKeyBottom.setBackground(new java.awt.Color(255, 255, 105));

        QuizAnswerKeyBottomLabel.setFont(new java.awt.Font("Tw Cen MT", 2, 24)); // NOI18N
        QuizAnswerKeyBottomLabel.setText("© QUIZ SYSTEM CREATED BY SHAFAY. ALL RIGHTS RESERVED!");

        javax.swing.GroupLayout QuizAnswerKeyBottomLayout = new javax.swing.GroupLayout(QuizAnswerKeyBottom);
        QuizAnswerKeyBottom.setLayout(QuizAnswerKeyBottomLayout);
        QuizAnswerKeyBottomLayout.setHorizontalGroup(
            QuizAnswerKeyBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, QuizAnswerKeyBottomLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(QuizAnswerKeyBottomLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 930, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );
        QuizAnswerKeyBottomLayout.setVerticalGroup(
            QuizAnswerKeyBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuizAnswerKeyBottomLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(QuizAnswerKeyBottomLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout QuizAnswerKeyLayout = new javax.swing.GroupLayout(QuizAnswerKey);
        QuizAnswerKey.setLayout(QuizAnswerKeyLayout);
        QuizAnswerKeyLayout.setHorizontalGroup(
            QuizAnswerKeyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(QuizAnswerKeyHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(QuizAnswerKeyQ1Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(QuizAnswerKeyQ5Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(QuizAnswerKeyQ2Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(QuizAnswerKeyQ3Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(QuizAnswerKeyQ4Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(QuizAnswerKeyLayout.createSequentialGroup()
                .addContainerGap(126, Short.MAX_VALUE)
                .addGroup(QuizAnswerKeyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, QuizAnswerKeyLayout.createSequentialGroup()
                        .addGroup(QuizAnswerKeyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator17, javax.swing.GroupLayout.PREFERRED_SIZE, 1104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(QuizAnswerKeySubmittedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 1116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(131, 131, 131))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, QuizAnswerKeyLayout.createSequentialGroup()
                        .addComponent(AnswerKeyNextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(586, 586, 586))))
            .addComponent(QuizAnswerKeyBottom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        QuizAnswerKeyLayout.setVerticalGroup(
            QuizAnswerKeyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, QuizAnswerKeyLayout.createSequentialGroup()
                .addComponent(QuizAnswerKeyHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(QuizAnswerKeySubmittedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator17, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(QuizAnswerKeyQ1Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(QuizAnswerKeyQ2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(QuizAnswerKeyQ3Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(QuizAnswerKeyQ4Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(QuizAnswerKeyQ5Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AnswerKeyNextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(QuizAnswerKeyBottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sidebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(QuizAnswerKey, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sidebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, 0)
                        .addComponent(QuizAnswerKey, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomeSideButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeSideButtonActionPerformed
        // TODO add your handling code here:
        new homepage().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_HomeSideButtonActionPerformed



    private void StartQuizSideButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartQuizSideButtonActionPerformed
        new QuizRegistration().setVisible(true);
        setVisible(false);
        // TODO add your handling code here:
  

    }//GEN-LAST:event_StartQuizSideButtonActionPerformed



    private void TeachersSideButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeachersSideButtonActionPerformed
        // TODO add your handling code here
        new TeachersData().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_TeachersSideButtonActionPerformed



    private void StudentsSideButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentsSideButtonActionPerformed
        // TODO add your handling code here:
        new StudentsData().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_StudentsSideButtonActionPerformed



    private void AboutUsSideButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutUsSideButtonActionPerformed
        // TODO add your handling
        new AboutUs().setVisible(true);
        setVisible(false);


    }//GEN-LAST:event_AboutUsSideButtonActionPerformed



    private void ExitSideButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitSideButtonActionPerformed
        // TODO add your handling code here:

        setVisible(false);
    }//GEN-LAST:event_ExitSideButtonActionPerformed

    private void ExitSideButtonPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitSideButtonPanelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ExitSideButtonPanelMouseClicked

    private void AnswerKeyNextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnswerKeyNextButtonActionPerformed
        // TODO add your handling code here:
        new QuizResult(q1StudentAnswer,q2StudentAnswer,q3StudentAnswer,q4StudentAnswer,q5StudentAnswer,q6StudentAnswer,q7StudentAnswer,CourseTopic1, numberofquestions,marksofquestions,day,month,year,hour,minute,mcq1,mcq1optA,mcq1optB,mcq1optC,mcq1optD,mcq1Correctopt,mcq2,mcq2optA,mcq2optB,mcq2optC,mcq2optD,mcq2Correctopt,mcq3,mcq3optA,mcq3optB,mcq3optC,mcq3optD,mcq3Correctopt,mcq4,mcq4optA,mcq4optB,mcq4optC,mcq4optD,mcq4Correctopt,tf1,tf1Correctopt,tf2,tf2Correctopt,tf3,tf3Correctopt,teacher,student,selectedCourse).setVisible(true);
        setVisible(false);

    }//GEN-LAST:event_AnswerKeyNextButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuizAnswerKey.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuizAnswerKey.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuizAnswerKey.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuizAnswerKey.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AboutUsSideButton;
    private javax.swing.JPanel AboutUsSideButtonPanel;
    private javax.swing.JButton AnswerKeyNextButton;
    private javax.swing.JButton ExitSideButton;
    private javax.swing.JPanel ExitSideButtonPanel;
    private javax.swing.JButton HomeSideButton;
    private javax.swing.JPanel HomeSideButtonPanel;
    private javax.swing.JPanel QuizAnswerKey;
    private javax.swing.JPanel QuizAnswerKeyBottom;
    private javax.swing.JLabel QuizAnswerKeyBottomLabel;
    private javax.swing.JPanel QuizAnswerKeyHeader;
    private javax.swing.JLabel QuizAnswerKeyHeaderLabel;
    private javax.swing.JLabel QuizAnswerKeyQ1CorrectAnswerLabel;
    private javax.swing.JLabel QuizAnswerKeyQ1Mcq1Label;
    private javax.swing.JPanel QuizAnswerKeyQ1Panel;
    private javax.swing.JLabel QuizAnswerKeyQ1YourAnswerLabel;
    private javax.swing.JLabel QuizAnswerKeyQ2CorrectAnswerLabel;
    private javax.swing.JLabel QuizAnswerKeyQ2Mcq3Label;
    private javax.swing.JPanel QuizAnswerKeyQ2Panel;
    private javax.swing.JLabel QuizAnswerKeyQ2YourAnswerLabel;
    private javax.swing.JLabel QuizAnswerKeyQ3CorrectAnswerLabel;
    private javax.swing.JPanel QuizAnswerKeyQ3Panel;
    private javax.swing.JLabel QuizAnswerKeyQ3Tf1Label;
    private javax.swing.JLabel QuizAnswerKeyQ3YourAnswerLabel;
    private javax.swing.JLabel QuizAnswerKeyQ4CorrectAnswerLabel;
    private javax.swing.JPanel QuizAnswerKeyQ4Panel;
    private javax.swing.JLabel QuizAnswerKeyQ4Tf3Label;
    private javax.swing.JLabel QuizAnswerKeyQ4YourAnswerLabel;
    private javax.swing.JLabel QuizAnswerKeyQ5CorrectAnswerLabel;
    private javax.swing.JLabel QuizAnswerKeyQ5Mcq2Label;
    private javax.swing.JPanel QuizAnswerKeyQ5Panel;
    private javax.swing.JLabel QuizAnswerKeyQ5YourAnswerLabel;
    private javax.swing.JLabel QuizAnswerKeyQ6CorrectAnswerLabel;
    private javax.swing.JPanel QuizAnswerKeyQ6Panel;
    private javax.swing.JLabel QuizAnswerKeyQ6Tf2Label;
    private javax.swing.JLabel QuizAnswerKeyQ6YourAnswerLabel;
    private javax.swing.JLabel QuizAnswerKeyQ7CorrectAnswerLabel;
    private javax.swing.JLabel QuizAnswerKeyQ7Mcq4Label;
    private javax.swing.JPanel QuizAnswerKeyQ7Panel;
    private javax.swing.JLabel QuizAnswerKeyQ7YourAnswerLabel;
    private javax.swing.JLabel QuizAnswerKeySubmittedLabel;
    private javax.swing.JLabel SideBarQuizLabel;
    private javax.swing.JButton StartQuizSideButton;
    private javax.swing.JPanel StartQuizSideButtonPanel;
    private javax.swing.JButton StudentsSideButton;
    private javax.swing.JPanel StudentsSideButtonPanel;
    private javax.swing.JButton TeachersSideButton;
    private javax.swing.JPanel TeachersSideButtonPanel;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel sidebar;
    // End of variables declaration//GEN-END:variables
}
