
package com.mycompany.projectguitrying;

/**
 *
 * @author SHAFAY
 */
public class QuizResult extends javax.swing.JFrame {

    /**
     * Creates new form QuizResult
     */
    String q1StudentAnswer;
    String q2StudentAnswer;
    String q3StudentAnswer;
    String q4StudentAnswer;
    String q5StudentAnswer;
    String q6StudentAnswer;
    String q7StudentAnswer;
    String numberofquestions;
    int marksofquestions;
    String day;
    String month;
    String year;
    String hour;
    String minute;
    String mcq1;
    String mcq1optA;
    String mcq1optB;
    String mcq1optC;
    String mcq1optD;
    String mcq1Correctopt;
    String mcq2;
    String mcq2optA;
    String mcq2optB;
    String mcq2optC;
    String mcq2optD;
    String mcq2Correctopt;
    String mcq3;
    String mcq3optA;
    String mcq3optB;
    String mcq3optC;
    String mcq3optD;
    String mcq3Correctopt;
    String mcq4;
    String mcq4optA;
    String mcq4optB;
    String mcq4optC;
    String mcq4optD;
    String mcq4Correctopt;
    String tf1;
    String tf1Correctopt;
    String tf2;
    String tf2Correctopt;
    String tf3;
    String tf3Correctopt;
    String teacher;
    String student;
    String selectedCourse;
    String CourseTopic1;


    public QuizResult(String q1StudentAnswer, String q2StudentAnswer, String q3StudentAnswer, String q4StudentAnswer, String q5StudentAnswer, String q6StudentAnswer, String q7StudentAnswer,String CourseTopic1, String numberofquestions, int marksofquestions, String day, String month, String year, String hour, String minute, String mcq1, String mcq1optA, String mcq1optB, String mcq1optC, String mcq1optD, String mcq1Correctopt, String mcq2, String mcq2optA, String mcq2optB, String mcq2optC, String mcq2optD, String mcq2Correctopt, String mcq3, String mcq3optA, String mcq3optB, String mcq3optC, String mcq3optD, String mcq3Correctopt, String mcq4, String mcq4optA, String mcq4optB, String mcq4optC, String mcq4optD, String mcq4Correctopt, String tf1, String tf1Correctopt, String tf2, String tf2Correctopt, String tf3, String tf3Correctopt, String teacher, String student, String selectedCourse) {

        this.CourseTopic1=CourseTopic1;
        this.q1StudentAnswer=q1StudentAnswer;
        this.q2StudentAnswer=q2StudentAnswer;
        this.q3StudentAnswer=q3StudentAnswer;
        this.q4StudentAnswer=q4StudentAnswer;
        this.q5StudentAnswer=q5StudentAnswer;
        this.q6StudentAnswer=q6StudentAnswer;
        this.q7StudentAnswer=q7StudentAnswer;
        this.mcq1=mcq1;
        this.mcq1optA=mcq1optA;
        this.mcq1optB=mcq1optB;
        this.mcq1optC=mcq1optC;
        this.mcq1optD=mcq1optD;
        this.mcq1Correctopt=mcq1Correctopt;
        this.mcq2=mcq2;
        this.mcq2optA=mcq2optA;
        this.mcq2optB=mcq2optB;
        this.mcq2optC=mcq2optC;
        this.mcq2optD=mcq2optD;
        this.mcq2Correctopt=mcq2Correctopt;
        this.mcq3=mcq3;
        this.mcq3optA=mcq3optA;
        this.mcq3optB=mcq3optB;
        this.mcq3optC=mcq3optC;
        this.mcq3optD=mcq3optD;
        this.mcq3Correctopt=mcq3Correctopt;
        this.mcq4=mcq4;
        this.mcq4optA=mcq4optA;
        this.mcq4optB=mcq4optB;
        this.mcq4optC=mcq4optC;
        this.mcq4optD=mcq4optD;
        this.mcq4Correctopt=mcq4Correctopt;
        this.tf1=tf1;
        this.tf1Correctopt=tf1Correctopt;
        this.tf2=tf2;
        this.tf2Correctopt=tf2Correctopt;
        this.tf3=tf3;
        this.tf3Correctopt=tf3Correctopt;
        this.teacher=teacher;
        this.student=student;
        this.selectedCourse=selectedCourse;
        this.numberofquestions = numberofquestions;
        this.marksofquestions = marksofquestions;
        this.day = day;
        this.month = month;
        this.year = year;
        this.hour = hour;
        this.minute = minute;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidebar = new javax.swing.JPanel();
        HomeSideButtonPanel = new javax.swing.JPanel();
        HomeSideButton = new javax.swing.JButton();
        StartQuizSideButtonPanel = new javax.swing.JPanel();
        StartQuizSideButton = new javax.swing.JButton();
        TeachersSideButtonPanel = new javax.swing.JPanel();
        TeachersSideButton = new javax.swing.JButton();
        StudentsSideButtonPanel = new javax.swing.JPanel();
        StudentsSideButton = new javax.swing.JButton();
        AboutUsSideButtonPanel = new javax.swing.JPanel();
        AboutUsSideButton = new javax.swing.JButton();
        SideBarQuizLabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        ExitSideButtonPanel = new javax.swing.JPanel();
        ExitSideButton = new javax.swing.JButton();
        QuizResult = new javax.swing.JPanel();
        QuizResultBottom = new javax.swing.JPanel();
        QuizResultBottomLabel = new javax.swing.JLabel();
        QuizResultHeader = new javax.swing.JPanel();
        QuizResultHeaderLabel = new javax.swing.JLabel();
        QuizResultStudentNameLabel = new javax.swing.JLabel();
        jSeparator18 = new javax.swing.JSeparator();
        QuizResultQuizCourseLabel = new javax.swing.JLabel();
        jSeparator19 = new javax.swing.JSeparator();
        QuizResultQuizTopicLabel = new javax.swing.JLabel();
        jSeparator20 = new javax.swing.JSeparator();
        QuizResultTotalMarksLabel = new javax.swing.JLabel();
        jSeparator21 = new javax.swing.JSeparator();
        QuizResultNumberOfQuestionsLabel = new javax.swing.JLabel();
        jSeparator22 = new javax.swing.JSeparator();
        QuizResultMarksOfQuestionsLabel = new javax.swing.JLabel();
        jSeparator23 = new javax.swing.JSeparator();
        jSeparator24 = new javax.swing.JSeparator();
        QuizResultObtainedMarksLabel = new javax.swing.JLabel();
        QuizResultObtainedPercentageLabel = new javax.swing.JLabel();
        jSeparator25 = new javax.swing.JSeparator();
        QuizResultObtainedGradeLabel = new javax.swing.JLabel();
        jSeparator26 = new javax.swing.JSeparator();
        QuizResultNextButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(50, 0));

        sidebar.setBackground(new java.awt.Color(255, 255, 105));
        sidebar.setBorder(javax.swing.BorderFactory.createMatteBorder(8, 8, 8, 8, new java.awt.Color(0, 0, 0)));

        HomeSideButtonPanel.setBackground(new java.awt.Color(255, 204, 0));


        HomeSideButton.setBackground(new java.awt.Color(255, 204, 0));
        HomeSideButton.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        HomeSideButton.setText("HOME");
        HomeSideButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        HomeSideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeSideButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout HomeSideButtonPanelLayout = new javax.swing.GroupLayout(HomeSideButtonPanel);
        HomeSideButtonPanel.setLayout(HomeSideButtonPanelLayout);
        HomeSideButtonPanelLayout.setHorizontalGroup(
            HomeSideButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeSideButtonPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(HomeSideButton, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        HomeSideButtonPanelLayout.setVerticalGroup(
            HomeSideButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomeSideButtonPanelLayout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(HomeSideButton)
                .addGap(15, 15, 15))
        );

        StartQuizSideButtonPanel.setBackground(new java.awt.Color(255, 204, 0));


        StartQuizSideButton.setBackground(new java.awt.Color(255, 205, 0));
        StartQuizSideButton.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        StartQuizSideButton.setText("START QUIZ");
        StartQuizSideButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        StartQuizSideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartQuizSideButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout StartQuizSideButtonPanelLayout = new javax.swing.GroupLayout(StartQuizSideButtonPanel);
        StartQuizSideButtonPanel.setLayout(StartQuizSideButtonPanelLayout);
        StartQuizSideButtonPanelLayout.setHorizontalGroup(
            StartQuizSideButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StartQuizSideButtonPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(StartQuizSideButton, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        StartQuizSideButtonPanelLayout.setVerticalGroup(
            StartQuizSideButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StartQuizSideButtonPanelLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(StartQuizSideButton)
                .addGap(14, 14, 14))
        );

        TeachersSideButtonPanel.setBackground(new java.awt.Color(255, 204, 0));


        TeachersSideButton.setBackground(new java.awt.Color(255, 205, 0));
        TeachersSideButton.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        TeachersSideButton.setText("TEACHERS");
        TeachersSideButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        TeachersSideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeachersSideButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TeachersSideButtonPanelLayout = new javax.swing.GroupLayout(TeachersSideButtonPanel);
        TeachersSideButtonPanel.setLayout(TeachersSideButtonPanelLayout);
        TeachersSideButtonPanelLayout.setHorizontalGroup(
            TeachersSideButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TeachersSideButtonPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(TeachersSideButton, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TeachersSideButtonPanelLayout.setVerticalGroup(
            TeachersSideButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TeachersSideButtonPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(TeachersSideButton)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        StudentsSideButtonPanel.setBackground(new java.awt.Color(255, 204, 0));


        StudentsSideButton.setBackground(new java.awt.Color(255, 205, 0));
        StudentsSideButton.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        StudentsSideButton.setText("STUDENTS");
        StudentsSideButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        StudentsSideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentsSideButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout StudentsSideButtonPanelLayout = new javax.swing.GroupLayout(StudentsSideButtonPanel);
        StudentsSideButtonPanel.setLayout(StudentsSideButtonPanelLayout);
        StudentsSideButtonPanelLayout.setHorizontalGroup(
            StudentsSideButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentsSideButtonPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(StudentsSideButton, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        StudentsSideButtonPanelLayout.setVerticalGroup(
            StudentsSideButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentsSideButtonPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(StudentsSideButton)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        AboutUsSideButtonPanel.setBackground(new java.awt.Color(255, 204, 0));


        AboutUsSideButton.setBackground(new java.awt.Color(255, 205, 0));
        AboutUsSideButton.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        AboutUsSideButton.setText("ABOUT US");
        AboutUsSideButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        AboutUsSideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutUsSideButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AboutUsSideButtonPanelLayout = new javax.swing.GroupLayout(AboutUsSideButtonPanel);
        AboutUsSideButtonPanel.setLayout(AboutUsSideButtonPanelLayout);
        AboutUsSideButtonPanelLayout.setHorizontalGroup(
            AboutUsSideButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AboutUsSideButtonPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(AboutUsSideButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AboutUsSideButtonPanelLayout.setVerticalGroup(
            AboutUsSideButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AboutUsSideButtonPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(AboutUsSideButton)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        SideBarQuizLabel.setFont(new java.awt.Font("Tw Cen MT", 3, 48)); // NOI18N
        SideBarQuizLabel.setText("QUIZ");

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N

        ExitSideButtonPanel.setBackground(new java.awt.Color(255, 204, 0));


        ExitSideButton.setBackground(new java.awt.Color(255, 205, 0));
        ExitSideButton.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        ExitSideButton.setText("EXIT");
        ExitSideButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        ExitSideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitSideButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ExitSideButtonPanelLayout = new javax.swing.GroupLayout(ExitSideButtonPanel);
        ExitSideButtonPanel.setLayout(ExitSideButtonPanelLayout);
        ExitSideButtonPanelLayout.setHorizontalGroup(
            ExitSideButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ExitSideButtonPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(ExitSideButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ExitSideButtonPanelLayout.setVerticalGroup(
            ExitSideButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ExitSideButtonPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(ExitSideButton)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout sidebarLayout = new javax.swing.GroupLayout(sidebar);
        sidebar.setLayout(sidebarLayout);
        sidebarLayout.setHorizontalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HomeSideButtonPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(TeachersSideButtonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(StartQuizSideButtonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(StudentsSideButtonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidebarLayout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addGroup(sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sidebarLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(SideBarQuizLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60))
            .addComponent(AboutUsSideButtonPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ExitSideButtonPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        sidebarLayout.setVerticalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarLayout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(SideBarQuizLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138)
                .addComponent(HomeSideButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StartQuizSideButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TeachersSideButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StudentsSideButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AboutUsSideButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ExitSideButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(160, Short.MAX_VALUE))
        );

        QuizResult.setBackground(new java.awt.Color(0, 0, 0));
        QuizResult.setBorder(javax.swing.BorderFactory.createMatteBorder(8, 0, 8, 8, new java.awt.Color(0, 0, 0)));

        QuizResultBottom.setBackground(new java.awt.Color(255, 255, 105));

        QuizResultBottomLabel.setFont(new java.awt.Font("Tw Cen MT", 2, 24)); // NOI18N
        QuizResultBottomLabel.setText("© QUIZ SYSTEM CREATED BY SHAFAY. ALL RIGHTS RESERVED!");

        javax.swing.GroupLayout QuizResultBottomLayout = new javax.swing.GroupLayout(QuizResultBottom);
        QuizResultBottom.setLayout(QuizResultBottomLayout);
        QuizResultBottomLayout.setHorizontalGroup(
            QuizResultBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, QuizResultBottomLayout.createSequentialGroup()
                .addGap(383, 383, 383)
                .addComponent(QuizResultBottomLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 930, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(309, 309, 309))
        );
        QuizResultBottomLayout.setVerticalGroup(
            QuizResultBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuizResultBottomLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(QuizResultBottomLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        QuizResultHeader.setBackground(new java.awt.Color(255, 255, 105));

        QuizResultHeaderLabel.setBackground(new java.awt.Color(255, 255, 105));
        QuizResultHeaderLabel.setFont(new java.awt.Font("Tw Cen MT", 3, 36)); // NOI18N
        QuizResultHeaderLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        QuizResultHeaderLabel.setText("QUIZ RESULT!");

        javax.swing.GroupLayout QuizResultHeaderLayout = new javax.swing.GroupLayout(QuizResultHeader);
        QuizResultHeader.setLayout(QuizResultHeaderLayout);
        QuizResultHeaderLayout.setHorizontalGroup(
            QuizResultHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuizResultHeaderLayout.createSequentialGroup()
                .addGap(628, 628, 628)
                .addComponent(QuizResultHeaderLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        QuizResultHeaderLayout.setVerticalGroup(
            QuizResultHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuizResultHeaderLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(QuizResultHeaderLabel)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        QuizResultStudentNameLabel.setBackground(new java.awt.Color(0, 0, 0));
        QuizResultStudentNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        QuizResultStudentNameLabel.setForeground(new java.awt.Color(255, 204, 51));
        QuizResultStudentNameLabel.setText("STUDENT NAME: "+student);

        jSeparator18.setForeground(new java.awt.Color(255, 255, 255));

        QuizResultQuizCourseLabel.setBackground(new java.awt.Color(0, 0, 0));
        QuizResultQuizCourseLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        QuizResultQuizCourseLabel.setForeground(new java.awt.Color(255, 204, 51));
        QuizResultQuizCourseLabel.setText("QUIZ COURSE: "+selectedCourse);

        jSeparator19.setForeground(new java.awt.Color(255, 255, 255));

        QuizResultQuizTopicLabel.setBackground(new java.awt.Color(0, 0, 0));
        QuizResultQuizTopicLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        QuizResultQuizTopicLabel.setForeground(new java.awt.Color(255, 204, 51));
        QuizResultQuizTopicLabel.setText("QUIZ TOPIC: "+CourseTopic1);

        jSeparator20.setForeground(new java.awt.Color(255, 255, 255));

        QuizResultTotalMarksLabel.setBackground(new java.awt.Color(0, 0, 0));
        QuizResultTotalMarksLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        QuizResultTotalMarksLabel.setForeground(new java.awt.Color(255, 204, 51));
        int totalmarks;
        if (numberofquestions=="3"){
            totalmarks=marksofquestions+marksofquestions+marksofquestions;
            QuizResultTotalMarksLabel.setText("TOTAL MARKS: "+totalmarks);
        }
        else if (numberofquestions=="4") {
            totalmarks=marksofquestions+marksofquestions+marksofquestions+marksofquestions;
            QuizResultTotalMarksLabel.setText("TOTAL MARKS: "+totalmarks);
        }
        else if (numberofquestions=="5") {
            totalmarks=marksofquestions+marksofquestions+marksofquestions+marksofquestions+marksofquestions;
            QuizResultTotalMarksLabel.setText("TOTAL MARKS: "+totalmarks);
        }
        else if (numberofquestions=="6") {
            totalmarks=marksofquestions+marksofquestions+marksofquestions+marksofquestions+marksofquestions+marksofquestions;
            QuizResultTotalMarksLabel.setText("TOTAL MARKS: "+totalmarks);
        }
        else {
            totalmarks=marksofquestions+marksofquestions+marksofquestions+marksofquestions+marksofquestions+marksofquestions+marksofquestions;
            QuizResultTotalMarksLabel.setText("TOTAL MARKS: "+totalmarks);
        }


        jSeparator21.setForeground(new java.awt.Color(255, 255, 255));

        QuizResultNumberOfQuestionsLabel.setBackground(new java.awt.Color(0, 0, 0));
        QuizResultNumberOfQuestionsLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        QuizResultNumberOfQuestionsLabel.setForeground(new java.awt.Color(255, 204, 51));
        QuizResultNumberOfQuestionsLabel.setText("NUMBER OF QUESTIONS: "+numberofquestions);

        jSeparator22.setForeground(new java.awt.Color(255, 255, 255));

        QuizResultMarksOfQuestionsLabel.setBackground(new java.awt.Color(0, 0, 0));
        QuizResultMarksOfQuestionsLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        QuizResultMarksOfQuestionsLabel.setForeground(new java.awt.Color(255, 204, 51));
        QuizResultMarksOfQuestionsLabel.setText("MARKS OF EACH QUESTION: "+marksofquestions);

        jSeparator23.setForeground(new java.awt.Color(255, 255, 255));

        jSeparator24.setForeground(new java.awt.Color(255, 255, 255));

        QuizResultObtainedMarksLabel.setBackground(new java.awt.Color(0, 0, 0));
        QuizResultObtainedMarksLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        QuizResultObtainedMarksLabel.setForeground(new java.awt.Color(255, 204, 51));

        int marks = 0;
        int q1Marks;
        int q2Marks;
        int q3Marks;
        int q4Marks;
        int q5Marks;
        int q6Marks;
        int q7Marks;

        if (numberofquestions=="3"){
            if (mcq1Correctopt==q1StudentAnswer){
                q1Marks=marksofquestions;
            }
            else {
                q1Marks=0;
            }
            if (mcq3Correctopt==q2StudentAnswer){
                q2Marks=marksofquestions;
            }
            else {
                q2Marks=0;
            }
            if (tf1Correctopt==q3StudentAnswer){
                q3Marks=marksofquestions;
            }
            else {
                q3Marks=0;
            }
            marks=q1Marks+q2Marks+q3Marks;
        }
        else if (numberofquestions=="4"){
            if (mcq1Correctopt==q1StudentAnswer){
                q1Marks=marksofquestions;
            }
            else {
                q1Marks=0;
            }
            if (mcq3Correctopt==q2StudentAnswer){
                q2Marks=marksofquestions;
            }
            else {
                q2Marks=0;
            }
            if (tf1Correctopt==q3StudentAnswer){
                q3Marks=marksofquestions;
            }
            else {
                q3Marks=0;
            }
            if (tf3Correctopt==q4StudentAnswer){
                q4Marks=marksofquestions;
            }
            else {
                q4Marks=0;
            }
            marks=q1Marks+q2Marks+q3Marks+q4Marks;
        }
        else if (numberofquestions=="5"){
            if (mcq1Correctopt==q1StudentAnswer){
                q1Marks=marksofquestions;
            }
            else {
                q1Marks=0;
            }
            if (mcq3Correctopt==q2StudentAnswer){
                q2Marks=marksofquestions;
            }
            else {
                q2Marks=0;
            }
            if (tf1Correctopt==q3StudentAnswer){
                q3Marks=marksofquestions;
            }
            else {
                q3Marks=0;
            }
            if (tf3Correctopt==q4StudentAnswer){
                q4Marks=marksofquestions;
            }
            else {
                q4Marks=0;
            }
            if (mcq2Correctopt==q5StudentAnswer){
                q5Marks=marksofquestions;
            }
            else {
                q5Marks=0;
            }
            marks=q1Marks+q2Marks+q3Marks+q4Marks+q5Marks;
        }
        else if (numberofquestions=="6"){
            if (mcq1Correctopt==q1StudentAnswer){
                q1Marks=marksofquestions;
            }
            else {
                q1Marks=0;
            }
            if (mcq3Correctopt==q2StudentAnswer){
                q2Marks=marksofquestions;
            }
            else {
                q2Marks=0;
            }
            if (tf1Correctopt==q3StudentAnswer){
                q3Marks=marksofquestions;
            }
            else {
                q3Marks=0;
            }
            if (tf3Correctopt==q4StudentAnswer){
                q4Marks=marksofquestions;
            }
            else {
                q4Marks=0;
            }
            if (mcq2Correctopt==q5StudentAnswer){
                q5Marks=marksofquestions;
            }
            else {
                q5Marks=0;
            }
            if (tf2Correctopt==q6StudentAnswer){
                q6Marks=marksofquestions;
            }
            else {
                q6Marks=0;
            }
            marks=q1Marks+q2Marks+q3Marks+q4Marks+q5Marks+q6Marks;
        }
        else{
            if (mcq1Correctopt==q1StudentAnswer){
                q1Marks=marksofquestions;
            }
            else {
                q1Marks=0;
            }
            if (mcq3Correctopt==q2StudentAnswer){
                q2Marks=marksofquestions;
            }
            else {
                q2Marks=0;
            }
            if (tf1Correctopt==q3StudentAnswer){
                q3Marks=marksofquestions;
            }
            else {
                q3Marks=0;
            }
            if (tf3Correctopt==q4StudentAnswer){
                q4Marks=marksofquestions;
            }
            else {
                q4Marks=0;
            }
            if (mcq2Correctopt==q5StudentAnswer){
                q5Marks=marksofquestions;
            }
            else {
                q5Marks=0;
            }
            if (tf2Correctopt==q6StudentAnswer){
                q6Marks=marksofquestions;
            }
            else {
                q6Marks=0;
            }
            if (mcq4Correctopt==q7StudentAnswer){
                q7Marks=marksofquestions;
            }
            else {
                q7Marks=0;
            }
            marks=q1Marks+q2Marks+q3Marks+q4Marks+q5Marks+q6Marks+q7Marks;
        }
        QuizResultObtainedMarksLabel.setText("OBTAINED MARKS: "+marks);

        QuizResultObtainedPercentageLabel.setBackground(new java.awt.Color(0, 0, 0));
        QuizResultObtainedPercentageLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        QuizResultObtainedPercentageLabel.setForeground(new java.awt.Color(255, 204, 51));
        float percent=marks/totalmarks;
        float percentage=percent*100;
        QuizResultObtainedPercentageLabel.setText("OBTAINED PERCENTAGE: "+percentage);

        jSeparator25.setForeground(new java.awt.Color(255, 255, 255));

        QuizResultObtainedGradeLabel.setBackground(new java.awt.Color(0, 0, 0));
        QuizResultObtainedGradeLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        QuizResultObtainedGradeLabel.setForeground(new java.awt.Color(255, 204, 51));
        if (percentage>=90 && percentage<=100){
            QuizResultObtainedGradeLabel.setText("OBTAINED GRADE: A+");
        }
        else if(percentage>=80 && percentage<=90) {
            QuizResultObtainedGradeLabel.setText("OBTAINED GRADE: A");
        }
        else if(percentage>=70 && percentage<=80) {
            QuizResultObtainedGradeLabel.setText("OBTAINED GRADE: B+");
        }
        else if(percentage>=60 && percentage<=70) {
            QuizResultObtainedGradeLabel.setText("OBTAINED GRADE: B");
        }
        else if(percentage>=50 && percentage<=60) {
            QuizResultObtainedGradeLabel.setText("OBTAINED GRADE: C");
        }
        else{
            QuizResultObtainedGradeLabel.setText("OBTAINED GRADE: D");
        }


        jSeparator26.setForeground(new java.awt.Color(255, 255, 255));

        QuizResultNextButton.setBackground(new java.awt.Color(255, 204, 0));
        QuizResultNextButton.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        QuizResultNextButton.setText("NEXT!");
        QuizResultNextButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        QuizResultNextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuizResultNextButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout QuizResultLayout = new javax.swing.GroupLayout(QuizResult);
        QuizResult.setLayout(QuizResultLayout);
        QuizResultLayout.setHorizontalGroup(
            QuizResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(QuizResultHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(QuizResultLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(QuizResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(QuizResultTotalMarksLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(QuizResultNumberOfQuestionsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(QuizResultMarksOfQuestionsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(QuizResultLayout.createSequentialGroup()
                        .addGroup(QuizResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator21, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(QuizResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(QuizResultStudentNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(QuizResultQuizCourseLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSeparator19, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSeparator20, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(QuizResultQuizTopicLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSeparator18, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator22, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator23, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator24, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator25, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator26, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(QuizResultObtainedMarksLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(QuizResultObtainedPercentageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(QuizResultObtainedGradeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, QuizResultLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(QuizResultNextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(825, 825, 825))
            .addComponent(QuizResultBottom, javax.swing.GroupLayout.PREFERRED_SIZE, 1385, Short.MAX_VALUE)
        );
        QuizResultLayout.setVerticalGroup(
            QuizResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, QuizResultLayout.createSequentialGroup()
                .addComponent(QuizResultHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(QuizResultStudentNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator18, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(QuizResultQuizCourseLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator19, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(QuizResultQuizTopicLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator20, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(QuizResultNumberOfQuestionsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator22, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(QuizResultMarksOfQuestionsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator23, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(QuizResultTotalMarksLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator21, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(QuizResultObtainedMarksLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator24, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(QuizResultObtainedPercentageLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator25, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(QuizResultObtainedGradeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator26, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(QuizResultNextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(QuizResultBottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sidebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(QuizResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(0, 0, 0)
                        .addComponent(QuizResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(sidebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomeSideButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeSideButtonActionPerformed
        // TODO add your handling code here:
        new homepage().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_HomeSideButtonActionPerformed


    private void StartQuizSideButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartQuizSideButtonActionPerformed

        // TODO add your handling code here:
        new QuizRegistration().setVisible(true);
        setVisible(false);


    }//GEN-LAST:event_StartQuizSideButtonActionPerformed


    private void TeachersSideButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeachersSideButtonActionPerformed
        // TODO add your handling code here
        new TeachersData().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_TeachersSideButtonActionPerformed


    private void StudentsSideButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentsSideButtonActionPerformed
        // TODO add your handling code here:
        new StudentsData().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_StudentsSideButtonActionPerformed


    private void AboutUsSideButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutUsSideButtonActionPerformed
        // TODO add your handling
        new AboutUs().setVisible(true);
        setVisible(false);


    }//GEN-LAST:event_AboutUsSideButtonActionPerformed


    private void ExitSideButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitSideButtonActionPerformed
        // TODO add your handling code here:

        setVisible(false);
    }//GEN-LAST:event_ExitSideButtonActionPerformed


    private void QuizResultNextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuizResultNextButtonActionPerformed
        // TODO add your handling code here:
        new QuizMarksheet(q1StudentAnswer,q2StudentAnswer,q3StudentAnswer,q4StudentAnswer,q5StudentAnswer,q6StudentAnswer,q7StudentAnswer,CourseTopic1, numberofquestions,marksofquestions,day,month,year,hour,minute,mcq1,mcq1optA,mcq1optB,mcq1optC,mcq1optD,mcq1Correctopt,mcq2,mcq2optA,mcq2optB,mcq2optC,mcq2optD,mcq2Correctopt,mcq3,mcq3optA,mcq3optB,mcq3optC,mcq3optD,mcq3Correctopt,mcq4,mcq4optA,mcq4optB,mcq4optC,mcq4optD,mcq4Correctopt,tf1,tf1Correctopt,tf2,tf2Correctopt,tf3,tf3Correctopt,teacher,student,selectedCourse).setVisible(true);
        setVisible(false);
        
    }//GEN-LAST:event_QuizResultNextButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuizResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuizResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuizResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuizResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public int marks;
    private javax.swing.JButton AboutUsSideButton;
    private javax.swing.JPanel AboutUsSideButtonPanel;
    private javax.swing.JButton ExitSideButton;
    private javax.swing.JPanel ExitSideButtonPanel;
    private javax.swing.JButton HomeSideButton;
    private javax.swing.JPanel HomeSideButtonPanel;
    private javax.swing.JPanel QuizResult;
    private javax.swing.JPanel QuizResultBottom;
    private javax.swing.JLabel QuizResultBottomLabel;
    private javax.swing.JPanel QuizResultHeader;
    private javax.swing.JLabel QuizResultHeaderLabel;
    private javax.swing.JLabel QuizResultMarksOfQuestionsLabel;
    private javax.swing.JButton QuizResultNextButton;
    private javax.swing.JLabel QuizResultNumberOfQuestionsLabel;
    private javax.swing.JLabel QuizResultObtainedGradeLabel;
    private javax.swing.JLabel QuizResultObtainedMarksLabel;
    private javax.swing.JLabel QuizResultObtainedPercentageLabel;
    private javax.swing.JLabel QuizResultQuizCourseLabel;
    private javax.swing.JLabel QuizResultQuizTopicLabel;
    private javax.swing.JLabel QuizResultStudentNameLabel;
    private javax.swing.JLabel QuizResultTotalMarksLabel;
    private javax.swing.JLabel SideBarQuizLabel;
    private javax.swing.JButton StartQuizSideButton;
    private javax.swing.JPanel StartQuizSideButtonPanel;
    private javax.swing.JButton StudentsSideButton;
    private javax.swing.JPanel StudentsSideButtonPanel;
    private javax.swing.JButton TeachersSideButton;
    private javax.swing.JPanel TeachersSideButtonPanel;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator21;
    private javax.swing.JSeparator jSeparator22;
    private javax.swing.JSeparator jSeparator23;
    private javax.swing.JSeparator jSeparator24;
    private javax.swing.JSeparator jSeparator25;
    private javax.swing.JSeparator jSeparator26;
    private javax.swing.JPanel sidebar;
    // End of variables declaration//GEN-END:variables
}
